import type { TopicRecord } from '@ci/content-schema'

/**
 * The topic registry.
 *
 * Topics are the conceptual index of the site. A topic explains a term or idea
 * in its own right, states what it is not, and points at the case sections and
 * objections where the argument is actually made.
 *
 * Two editorial rules govern this file. First, Hades, Sheol, Gehenna and the
 * lake of fire are kept genuinely distinct from one another and from the English
 * word "hell"; every one of those four records says what it is and what it is
 * not. Second, eternal conscious torment and universal reconciliation are stated
 * as their own adherents would recognise them before this site's disagreement is
 * recorded.
 */
export const TOPIC_RECORDS: readonly TopicRecord[] = [
  {
    id: 'conditional-immortality',
    slug: 'conditional-immortality',
    title: 'Conditional Immortality',
    definition:
      'The view that immortality is not native to human beings but is given by God through Christ, so that those who are finally lost do not live for ever but perish.',
    body: [
      'Conditional immortality holds that continued existence is a gift rather than a possession. Scripture attributes immortality to God alone and describes it as brought to light through the gospel, which locates endless life in what God gives rather than in what every creature owns by nature.',
      'On this view the unrighteous are raised, judged, and punished consciously, and the punishment culminates in death. The position is not a claim that judgment is painless, brief, or a quiet fading away at the moment a person dies.',
      'The name marks what is at stake. What is conditional is immortality itself: it depends on union with the Christ who alone has abolished death. Conditionalists differ among themselves on several details, and this site says so where they do.',
    ],
    aliases: ['CI', 'conditionalism', 'evangelical conditionalism', 'conditional immortality'],
    relatedTerms: [
      'annihilationism',
      'immortality',
      'eternal-life',
      'second-death',
      'resurrection',
      'destruction',
    ],
    distinctions: [
      'Conditional immortality is not the claim that there is no hell and no final judgment.',
      'It is not universal reconciliation, because those who are lost are not finally saved.',
      'It is not the claim that the wicked simply cease to exist when they die, without judgment.',
      'It is not a position on whether the dead are conscious before the resurrection.',
    ],
    principalPassages: [
      '1 Timothy 6:15-16',
      '2 Timothy 1:10',
      'Romans 2:7',
      '1 Corinthians 15:50-54',
      'John 3:16',
    ],
    relatedSections: ['S22', 'RB2', 'S21', 'S11', 'RB1'],
    relatedObjections: ['S30', 'S31', 'S28'],
    sourceIds: [
      'dear-bible-teaches-annihilationism',
      'wenham-case-for-conditional-immortality',
      'afterlife-god-alone-is-immortal',
      'welch-source-document',
    ],
    openQuestions: [
      'How long the unrighteous consciously exist between the resurrection and the second death.',
      'Whether the fate of Satan and the fallen angels differs from that of human beings.',
    ],
  },
  {
    id: 'annihilationism',
    slug: 'annihilationism',
    title: 'Annihilationism',
    definition:
      'A family of views holding that those who are finally impenitent are destroyed rather than kept alive in unending torment. Conditional immortality is one form of it.',
    body: [
      'Annihilationism names an outcome rather than a route to it. Writers reach the same conclusion by different paths: some argue from the biblical vocabulary of destruction, some from what Scripture says about the soul, and some from eternal punishment understood as a permanent result rather than a continuing act.',
      'Because the label covers several positions, this site prefers conditional immortality when describing its own view. Conditional immortality adds a specific claim about where immortality comes from, and not every annihilationist makes that claim.',
      'The word also carries a misleading suggestion, since it can be heard as the lost being quietly switched off. The position argued here involves resurrection, judgment, and a punishment that is consciously experienced before it ends.',
    ],
    aliases: ['annihilation', 'annihilation view', 'extinctionism', 'destructionism'],
    relatedTerms: [
      'conditional-immortality',
      'destruction',
      'second-death',
      'eternal-conscious-torment',
      'death',
    ],
    distinctions: [
      'Annihilationism is a broader label than conditional immortality and covers several distinct positions.',
      'It is not a claim that final punishment is instantaneous or that it involves no suffering.',
      'It is not universalism, although both reject unending conscious torment.',
    ],
    principalPassages: [
      'Matthew 10:28',
      '2 Peter 2:6',
      'Malachi 4:1-3',
      '2 Thessalonians 1:9',
      'Psalms 37:20',
    ],
    relatedSections: ['RB1', 'S08', 'S10', 'S22', 'S04'],
    relatedObjections: ['S30', 'S31'],
    sourceIds: [
      'dear-bible-teaches-annihilationism',
      'fudge-fire-that-consumes',
      'themelios-destroyed-for-ever',
    ],
    openQuestions: [
      'Whether the label helps or hinders, given how often it is heard as painless extinction.',
    ],
  },
  {
    id: 'eternal-conscious-torment',
    slug: 'eternal-conscious-torment',
    title: 'Eternal Conscious Torment',
    definition:
      'The view, held by the majority of the Western church for many centuries, that those who die outside Christ are raised and consciously suffer the just judgment of God without end.',
    body: [
      'Defenders of eternal conscious torment hold that final punishment is a condition rather than an event. The lost are raised, judged, and consigned to conscious loss and suffering that has no end. This is understood as the settled verdict of a holy God on sin, not as cruelty, and its defenders take no pleasure in it.',
      'The case is usually built from Matthew 25:46, where eternal punishment stands in parallel with eternal life; from Revelation 14:11 and 20:10; and from Mark 9:48, where the worm does not die and the fire is not quenched. Many defenders add that sin against a God of infinite worth incurs a penalty no finite creature can discharge, and that the historic and confessional weight behind the doctrine should not be set aside lightly.',
      'This site disagrees. It argues that the punishment named in those texts is destruction whose result is permanent, rather than a punishing that continues without end. The disagreement is about what the punishment is. It is not a disagreement about whether God judges, and it is not a judgement about the motives of those who hold the traditional view.',
    ],
    aliases: [
      'ECT',
      'traditional view',
      'traditionalism',
      'eternal torment',
      'everlasting conscious punishment',
    ],
    relatedTerms: [
      'punishment',
      'eternal-and-everlasting',
      'final-judgment',
      'conditional-immortality',
      'immortality',
      'universal-reconciliation',
    ],
    distinctions: [
      'Eternal conscious torment is a claim about duration and consciousness, not only about severity.',
      'It is not the same as affirming that hell is real, which every view on this site affirms.',
      'Its defenders do not generally teach that demons torture the lost; the punishment is God’s just sentence.',
      'It is not the popular imagery of pitchforks, caves and gleeful devils, which its defenders reject as well.',
    ],
    principalPassages: [
      'Matthew 25:46',
      'Revelation 14:9-11',
      'Revelation 20:10',
      'Mark 9:42-48',
      'Daniel 12:2',
    ],
    relatedSections: ['RB3', 'S12', 'S04', 'S02', 'S03'],
    relatedObjections: ['S29', 'S30', 'S31', 'S34'],
    sourceIds: [
      'macarthur-truth-about-hell',
      'edwards-justice-of-god',
      'aquinas-summa-1a2ae-87',
      'themelios-destroyed-for-ever',
    ],
    openQuestions: [
      'How far the argument from the dignity of the one offended is load-bearing for its defenders.',
      'Whether the claim that the lost keep sinning after judgment is required by the position or optional to it.',
    ],
  },
  {
    id: 'universal-reconciliation',
    slug: 'universal-reconciliation',
    title: 'Universal Reconciliation',
    definition:
      'The view that God will finally reconcile every person to himself, so that punishment after death is corrective and temporary and no one is lost for ever.',
    body: [
      'Its defenders hold this as a conclusion drawn from Scripture rather than as sentiment. They point to the texts that speak of God being all in all, of all things being united under Christ, and of one act of righteousness bringing justification and life for all, and they read punishment after death as discipline that achieves what it is for.',
      'They generally affirm judgment, wrath, and the seriousness of sin. What they deny is that the outcome of judgment is either unending torment or the end of a person. On their reading the fire refines rather than consumes, and the last word belongs to mercy.',
      'This site does not teach universal salvation, and holds that the universal-sounding texts are bounded by their own contexts. It does observe that such language reads more naturally in a final state where rebellion has ended than in one where rebellion continues for ever.',
    ],
    aliases: [
      'universalism',
      'universal salvation',
      'Christian universalism',
      'apokatastasis',
      'ultimate reconciliation',
    ],
    relatedTerms: [
      'eternal-conscious-torment',
      'conditional-immortality',
      'punishment',
      'final-judgment',
      'eternal-life',
    ],
    distinctions: [
      'Universal reconciliation denies that anyone is finally lost; conditional immortality does not.',
      'It treats punishment as corrective, where this site treats it as retributive and final.',
      'It is not the same claim as post-mortem conversion, although the two are often held together.',
      'Rejecting eternal conscious torment does not by itself commit anyone to universalism.',
    ],
    principalPassages: [
      '1 Corinthians 15:20-28',
      'Ephesians 1:10',
      'Romans 5:18',
      'Romans 11:32',
      'Philippians 2:10-11',
    ],
    relatedSections: ['S25', 'S26', 'S27', 'P00'],
    relatedObjections: ['S30'],
    sourceIds: [
      'dear-bible-teaches-annihilationism',
      'welch-source-document',
      'anthem-eastside-three-views',
    ],
    openQuestions: [
      'Whether the parable of the unforgiving servant tells against a debt discharged by suffering.',
      'How far reaction against eternal conscious torment has driven the modern revival of the view.',
    ],
  },
  {
    id: 'immortality',
    slug: 'immortality',
    title: 'Immortality',
    definition:
      'Deathlessness. In Scripture it is attributed to God alone and is presented as something human beings seek and receive rather than something they hold by nature.',
    body: [
      'Paul writes that God alone has immortality, and that Christ brought life and immortality to light through the gospel. Elsewhere immortality is sought by patience in well doing, and the perishable puts on the imperishable at the resurrection. That pattern places immortality in the gift rather than in the creature.',
      'The alternative view holds that human beings, uniquely among earthly creatures, are made for endless existence, so that the only question at judgment is where a person spends eternity rather than whether they continue at all. On that reading the image of God carries deathlessness with it.',
      'Scripture never defines the image of God as inherent immortality, and it describes human life as grass, breath, mist and a passing shadow. Whether the soul is naturally deathless is the hinge on which much of this debate turns, which is why it is treated before the disputed passages rather than after them.',
    ],
    aliases: ['deathlessness', 'immortal soul', 'imperishability', 'athanasia'],
    relatedTerms: [
      'conditional-immortality',
      'eternal-life',
      'resurrection',
      'death',
      'tree-of-life',
      'body-soul-and-spirit',
    ],
    distinctions: [
      'Immortality is not the same as eternal life, which includes quality and relationship as well as duration.',
      'Surviving into the intermediate state is not the same as being immortal by nature.',
      'The imperishable body of 1 Corinthians 15 is promised to those raised in Christ, not to everyone raised.',
    ],
    principalPassages: [
      '1 Timothy 6:15-16',
      '2 Timothy 1:10',
      'Romans 2:7',
      '1 Corinthians 15:50-54',
      '1 Peter 1:23-24',
    ],
    relatedSections: ['RB2', 'S22', 'S21', 'S09'],
    relatedObjections: ['S31', 'S32'],
    sourceIds: [
      'afterlife-god-alone-is-immortal',
      'dear-bible-teaches-annihilationism',
      'irenaeus-against-heresies',
    ],
    openQuestions: [
      'How God sustains the unrighteous between death and the final judgment.',
      'How much Greek philosophy shaped later Christian teaching on the soul, which historians dispute.',
      'Whether angels are immortal by nature, which Scripture does not state directly.',
    ],
  },
  {
    id: 'eternal-life',
    slug: 'eternal-life',
    title: 'Eternal Life',
    definition:
      'The life of the age to come, given by God through Jesus Christ. It is unending in duration and different in kind from present life, and it is the stated alternative to perishing.',
    body: [
      'Jesus defines eternal life as knowing the Father and the Son, which makes it a quality of life and not only a length of it. It is described as given, entered, inherited and received, never as something every person already holds and merely relocates at death.',
      'When the New Testament names the alternative to eternal life it reaches for the language of losing life: perishing, death, not seeing life, passing away, wrath, condemnation, destruction, and eternal punishment. Reading one item on that list as unending conscious existence makes it the odd one out among the rest.',
      'Both sides agree that eternal life lasts for ever. The disagreement is over what stands opposite it, and whether that opposite is a continuing experience or a permanent outcome.',
    ],
    aliases: ['everlasting life', 'life of the age to come', 'zoe aionios'],
    relatedTerms: [
      'immortality',
      'perishing',
      'death',
      'eternal-and-everlasting',
      'resurrection',
      'tree-of-life',
    ],
    distinctions: [
      'Eternal life is not merely endless duration, or the lost would have it too on the traditional view.',
      'It is not the same as the immortality of the soul, which Scripture does not attribute to human nature.',
      'It is not a reward earned; the New Testament calls it a gift.',
    ],
    principalPassages: [
      'John 3:16',
      'John 17:3',
      'John 10:10',
      'Romans 6:23',
      'Matthew 25:46',
      'John 3:36',
    ],
    relatedSections: ['S11', 'S04', 'S22', 'S19', 'S20'],
    relatedObjections: ['S29', 'S34'],
    sourceIds: ['dear-bible-teaches-annihilationism', 'welch-source-document'],
    openQuestions: [],
  },
  {
    id: 'death',
    slug: 'death',
    title: 'Death',
    definition:
      'The end of life. Scripture names death as the wage of sin, and uses the word both of the death every person dies and of the final loss that death pictures.',
    body: [
      'From the garden onward the penalty Scripture names for sin is death. Because those in Christ still die physically and the unrighteous also die physically, the penalty in view cannot be only the first death. Revelation gives the final penalty its own name: the second death.',
      'Defenders of eternal conscious torment generally read death in these texts as separation from God rather than the end of life, so that the second death is permanent separation consciously experienced. Separation is genuinely part of what death means, and conditionalism does not deny it.',
      'The reply offered here is that separation from the one in whom all things hold together does not leave a creature sustained. And death is a thing every reader already understands, which makes it a strange word to choose for unending conscious life if that is what was meant.',
    ],
    aliases: ['dying', 'mortality', 'the first death', 'thanatos'],
    relatedTerms: [
      'second-death',
      'destruction',
      'perishing',
      'punishment',
      'intermediate-state',
      'resurrection',
    ],
    distinctions: [
      'Physical death is not the second death, which follows the resurrection and the judgment.',
      'Death as separation and death as the end of life are not mutually exclusive readings.',
      'Spiritual death before conversion is a present condition, not the final sentence.',
    ],
    principalPassages: [
      'Romans 6:23',
      'Genesis 2:17',
      'Ezekiel 18:20',
      'James 1:15',
      'Revelation 20:14',
    ],
    relatedSections: ['S07', 'S18', 'S17', 'S16', 'S10'],
    relatedObjections: ['S30'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [
      'Whether the death threatened in Genesis 2:17 is primarily spiritual, physical, or both at once.',
    ],
  },
  {
    id: 'second-death',
    slug: 'second-death',
    title: 'The Second Death',
    definition:
      'The phrase Revelation uses for the outcome of the last judgment. It names the lake of fire, and it is distinguished from the death every person dies before the resurrection.',
    body: [
      'Revelation supplies its own gloss: the lake of fire is the second death. The phrase appears where Death and Hades are destroyed, where those not written in the book of life are thrown in, and in the list of those whose portion is the lake that burns with fire and sulphur.',
      'For the phrase to mean anything, something must happen that did not already happen at the first death. The unrighteous have already died once and have already been separated from God by sin, so a second death that only continues that condition is hard to account for.',
      'The traditional reading takes the second death as permanent separation from God, consciously experienced. The conditionalist reading takes it as a real death following the resurrection, permanent because no further resurrection lies beyond it.',
    ],
    aliases: ['the second death', 'deuteros thanatos'],
    relatedTerms: ['lake-of-fire', 'death', 'final-judgment', 'destruction', 'resurrection'],
    distinctions: [
      'The second death is not the intermediate state, which precedes the resurrection.',
      'It is not physical death, which the righteous and the unrighteous both undergo.',
      'Revelation applies the phrase to the lake of fire itself, not to a separate place called hell.',
    ],
    principalPassages: [
      'Revelation 20:14',
      'Revelation 21:8',
      'Revelation 2:11',
      'Revelation 20:6',
      'Romans 6:23',
    ],
    relatedSections: ['S03', 'S07', 'S18', 'S24', 'S10'],
    relatedObjections: ['S28', 'S30'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [],
  },
  {
    id: 'destruction',
    slug: 'destruction',
    title: 'Destruction',
    definition:
      'The dominant biblical vocabulary for the end of the wicked. The words cover ruin as well as cessation, and the texts add language of completeness that ruin alone does not explain.',
    body: [
      'Across the Psalms, the Prophets, the Gospels and the Epistles the fate of the wicked is described as being destroyed, consumed, cut off, burned up, made to vanish and brought to nothing. This is the ordinary language of Scripture on the subject, and it runs in one direction.',
      'Defenders of the traditional view answer that destruction can mean ruin: a wrecked building is destroyed and still stands. That is a real sense of the word group, and conditionalists do not deny it.',
      'The reply is that several texts add a finality ruin does not account for. Not a root or a branch left, consumed until they are no more, as though they had never been, ashes underfoot. And the same word is used of the wicked and of irrational animals, which nobody supposes are tormented for ever.',
    ],
    aliases: ['destroy', 'destroyed', 'ruin', 'olethros', 'apoleia'],
    relatedTerms: ['perishing', 'death', 'fire', 'second-death', 'punishment', 'annihilationism'],
    distinctions: [
      'Destroying a person is not the same as removing every particle of matter from the universe.',
      'Ruin and cessation are both possible senses, and context rather than etymology decides which is in view.',
      'That ashes remain is not evidence that anyone consciously remains.',
    ],
    principalPassages: [
      'Psalms 37:20',
      'Malachi 4:1-3',
      '2 Peter 3:7',
      '2 Thessalonians 1:9',
      'Matthew 10:28',
      'Philippians 3:18-19',
    ],
    relatedSections: ['S08', 'S04', 'S13', 'S10', 'S11'],
    relatedObjections: ['S30', 'S31'],
    sourceIds: ['dear-bible-teaches-annihilationism', 'bible-gateway'],
    openQuestions: [],
  },
  {
    id: 'perishing',
    slug: 'perishing',
    title: 'Perishing',
    definition:
      'The word set most often paired with eternal life in the New Testament. It covers losing, being lost, and being destroyed, and it is used of people, animals and things alike.',
    body: [
      'John 3:16 sets perishing against eternal life, and the same word group recurs wherever the alternative to life is named. It is also the verb Jesus uses in Matthew 10:28 for what God is able to do to soul and body, which ties the two discussions together.',
      'The word has a genuine range. It can mean to lose something, as with a lost coin or a lost sheep, and it can mean to put a person to death. Its sense in any given verse is settled by the sentence it stands in, not by its most dramatic possible meaning.',
      'Traditional interpreters read perishing as ruin, so that the person is lost to God without ceasing to be. Conditionalists read it alongside the destruction vocabulary that surrounds it, and note the company it keeps in the list of contrasts with eternal life.',
    ],
    aliases: ['perish', 'apollumi', 'lost', 'destroy'],
    relatedTerms: ['destruction', 'eternal-life', 'death', 'second-death'],
    distinctions: [
      'Perishing in the sense of being lost and perishing in the sense of dying are both attested uses.',
      'A lost sheep can be recovered; the contrast with eternal life is not framed as recoverable.',
      'The word cannot settle the question on its own, in either direction.',
    ],
    principalPassages: [
      'John 3:16',
      'Matthew 10:28',
      'Luke 13:3',
      '2 Peter 3:9',
      'Matthew 7:13-14',
    ],
    relatedSections: ['S11', 'S08', 'S10'],
    relatedObjections: ['S30'],
    sourceIds: ['dear-bible-teaches-annihilationism', 'rethinking-hell'],
    openQuestions: [],
  },
  {
    id: 'fire',
    slug: 'fire',
    title: 'Fire',
    definition:
      'The most common image for divine judgment in Scripture. Its ordinary function in the biblical texts is to consume what is put into it.',
    body: [
      'Fire in Scripture burns things up. Chaff, stubble, weeds, thorns and fruitless trees: the harvest images in the Gospels all end with the useless part destroyed rather than preserved. Fire paired with sulphur consistently marks complete and irreversible destruction.',
      'Where something in a fire is not consumed, the text marks that as remarkable and credits it to God. The bush burns and is not consumed; the three men walk in the furnace unharmed. Preservation in fire is presented as an exception requiring divine action, never as what fire ordinarily does.',
      'Defenders of the traditional view answer that the fire of final judgment is unlike ordinary fire in any case, and that God is entirely able to sustain a person within it. Conditionalists grant the ability and question the picture, since Scripture nowhere describes fire as a preservative.',
    ],
    aliases: ['flames', 'burning', 'fiery furnace', 'unquenchable fire', 'eternal fire'],
    relatedTerms: [
      'lake-of-fire',
      'gehenna',
      'destruction',
      'sodom-and-gomorrah',
      'final-judgment',
    ],
    distinctions: [
      'Unquenchable fire is fire nobody can put out, which is not the same as fire that never goes out.',
      'Eternal fire in Jude describes a fire whose effect is permanent, not one still burning today.',
      'Refining fire that purifies and consuming fire that destroys are different images with different objects.',
    ],
    principalPassages: [
      'Matthew 13:24-43',
      'Malachi 4:1-3',
      'Hebrews 12:29',
      'Mark 9:42-48',
      'Jude 7',
    ],
    relatedSections: ['S13', 'S01', 'S03', 'S14', 'S02'],
    relatedObjections: ['S30'],
    sourceIds: [
      'dear-bible-teaches-annihilationism',
      'rethinking-hell-fire-not-quenched',
      'rethinking-hell-worm-does-not-die',
    ],
    openQuestions: [
      'Whether the lake of fire is a literal fire or a symbolic image within a symbolic vision.',
    ],
  },
  {
    id: 'eternal-and-everlasting',
    slug: 'eternal-and-everlasting',
    title: 'Eternal and Everlasting',
    definition:
      'The adjective used of both life and punishment in Matthew 25:46. It can mark unending duration and it can mark the age to come, and in the New Testament it often qualifies a result that stands permanently.',
    body: [
      'Other eternal things in the New Testament are accomplished once and stand for ever: eternal salvation, eternal redemption, eternal inheritance, eternal judgment. The saving, redeeming, inheriting and judging happen at a point; what is eternal is the result.',
      'That pattern matters for eternal punishment, which is a noun of result rather than a verb of continuing activity. Conditionalists affirm that the punishment is eternal, and understand the punishment itself to be a destruction whose effect never reverses.',
      'None of this shows that the adjective cannot mean everlasting duration. It often does, and it plainly does of eternal life. The argument concerns what each noun names, not whether the adjective is strong.',
    ],
    aliases: ['eternal', 'everlasting', 'aionios', 'for ever and ever', 'age to come'],
    relatedTerms: ['punishment', 'eternal-life', 'destruction', 'final-judgment', 'fire'],
    distinctions: [
      'Eternal punishment and eternal punishing are different claims, and the texts use the noun.',
      'Eternal in the sense of the age to come is a qualitative use, not a denial of duration.',
      'Smoke rising for ever and ever is said in Scripture of places whose destruction is already complete.',
    ],
    principalPassages: [
      'Matthew 25:46',
      'Hebrews 5:9',
      'Hebrews 9:12',
      'Hebrews 6:2',
      'Jude 7',
      '2 Thessalonians 1:9',
    ],
    relatedSections: ['S04', 'S02', 'S14', 'S01'],
    relatedObjections: ['S30'],
    sourceIds: ['dear-bible-teaches-annihilationism', 'rethinking-hell-2-thess-1-9-part-2'],
    openQuestions: [
      'Whether any single English word carries both the durational and the qualitative sense well.',
    ],
  },
  {
    id: 'punishment',
    slug: 'punishment',
    title: 'Punishment',
    definition:
      'What God justly imposes at the last judgment. Scripture grades it by what the sinner knew and could have known, and names its final form as death and destruction.',
    body: [
      'Both views agree that God will punish perfectly, neither too little nor too much. The disagreement is over what the punishment is: an act of punishing that continues without end, or a sentence carried out whose result is permanent.',
      'Scripture repeatedly calibrates judgment by circumstance. Fewer blows and more blows; more bearable for one town than another; guilt incurred where there was knowledge and withheld where there was none. That grading sits awkwardly with a penalty fixed only by the dignity of the one offended.',
      'The infinite-offence argument is offered by its own defenders as reasoning about God rather than as exegesis of a text. It is a serious argument, and it is answered on its own terms here rather than waved away.',
    ],
    aliases: ['penalty', 'retribution', 'wrath', 'kolasis', 'final punishment'],
    relatedTerms: [
      'final-judgment',
      'death',
      'destruction',
      'eternal-and-everlasting',
      'eternal-conscious-torment',
    ],
    distinctions: [
      'Punishment as a result and punishing as an activity are different things, and Matthew 25:46 uses the noun.',
      'Degrees of punishment are affirmed by both views and are difficult to express if every outcome is identical.',
      'Suffering that accompanies judgment is not the same as suffering that discharges a debt.',
    ],
    principalPassages: [
      'Matthew 25:46',
      'Luke 12:47-48',
      'Matthew 11:20-24',
      '2 Corinthians 5:10',
      '2 Thessalonians 1:9',
    ],
    relatedSections: ['RB3', 'S04', 'S23', 'S26', 'S07'],
    relatedObjections: ['S30', 'S32'],
    sourceIds: [
      'dear-bible-teaches-annihilationism',
      'rethinking-hell-finite-sins',
      'macarthur-truth-about-hell',
      'aquinas-summa-1a2ae-87',
    ],
    openQuestions: [
      'Whether an infinite punishment paid out over unending time is ever actually administered.',
    ],
  },
  {
    id: 'final-judgment',
    slug: 'final-judgment',
    title: 'The Final Judgment',
    definition:
      'The judgment of all people after the resurrection, described in Scripture as a day on which the books are opened and each person receives what is due for what was done.',
    body: [
      'Scripture speaks of a day of judgment, and Jesus can say that the day will be more bearable for one place than for another. That treats what happens on the day as itself the reckoning, rather than as the doorway to a sentence still being served.',
      'The same day is called the day of judgment and of the destruction of the ungodly, which places verdict and outcome on one occasion. Hebrews sets a single appointment: it is appointed for people to die once, and after that comes judgment.',
      'How long the day lasts is not stated, and this site does not claim to know. What the texts tie together is the sentence and its execution.',
    ],
    aliases: ['last judgment', 'judgment day', 'great white throne', 'day of judgment'],
    relatedTerms: ['day-of-the-lord', 'resurrection', 'punishment', 'second-death', 'lake-of-fire'],
    distinctions: [
      'The final judgment follows the resurrection, so it is later than the intermediate state.',
      'Judgment and the carrying out of the sentence are distinguishable, though Scripture sets them on one day.',
      'A judgment of works is affirmed for the righteous too, and is not the same as condemnation.',
    ],
    principalPassages: [
      'Revelation 20:11-15',
      '2 Peter 3:7',
      'Hebrews 9:27',
      'Matthew 25:31-46',
      'Romans 2:5-6',
    ],
    relatedSections: ['S23', 'S03', 'S06', 'S20', 'S09'],
    relatedObjections: ['S28', 'S30'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [
      'The literal duration of the day of judgment, which Scripture does not specify.',
    ],
  },
  {
    id: 'resurrection',
    slug: 'resurrection',
    title: 'Resurrection',
    definition:
      'The raising of the dead in bodily form. Scripture describes a resurrection of both the righteous and the unrighteous, and only the former is said to be raised imperishable.',
    body: [
      'Daniel speaks of many who sleep in the dust awaking, some to everlasting life and some to shame and everlasting contempt. John records Jesus speaking of a resurrection of life and a resurrection of judgment. Everyone is raised; not everyone is raised to the same thing.',
      'Paul describes the resurrection body of those in Christ: sown perishable and raised imperishable, the mortal putting on immortality. He does not extend that description to the unrighteous, and he says the perishable does not inherit the imperishable.',
      'On the conditionalist reading this is where immortality is actually conferred, and it is conferred on those who belong to Christ. The unrighteous are raised to face judgment, not granted a body that cannot die.',
    ],
    aliases: ['raising of the dead', 'bodily resurrection', 'anastasis'],
    relatedTerms: [
      'immortality',
      'final-judgment',
      'intermediate-state',
      'eternal-life',
      'body-soul-and-spirit',
    ],
    distinctions: [
      'The resurrection is not the intermediate state, which is the period before it.',
      'Being raised is not the same as being made imperishable, which Paul reserves for those in Christ.',
      'The resurrection of judgment is a real bodily raising, not a figure of speech for condemnation.',
    ],
    principalPassages: [
      '1 Corinthians 15:35-57',
      'Daniel 12:2',
      'John 5:28-29',
      'Acts 24:15',
      '1 Corinthians 15:42-43',
    ],
    relatedSections: ['S22', 'S09', 'S23', 'S01'],
    relatedObjections: ['S30'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [
      'The nature of the resurrection body of the unrighteous, which Scripture does not describe.',
    ],
  },
  {
    id: 'hades',
    slug: 'hades',
    title: 'Hades',
    definition:
      'The Greek term for the realm of the dead, used in the New Testament and in the Greek Old Testament, where it usually renders the Hebrew Sheol. It is the state of the dead before the resurrection.',
    body: [
      'Hades is where the dead are. It is not where the last judgment is carried out. In the account of the rich man and Lazarus, the rich man is in Hades in torment while his five brothers are still alive on earth, which places the whole scene before the resurrection and before the judgment.',
      'Revelation makes the point unmistakable. Death and Hades give up the dead who are in them, and are then themselves thrown into the lake of fire. Whatever Hades is, it is emptied and abolished, so it cannot be anyone’s final state.',
      'What Hades is not: it is not Gehenna, the word Jesus uses for final destruction; it is not the lake of fire, into which Hades itself is thrown; and it is not what most modern readers mean by hell. Rendering it hell collapses a temporary condition into a final one.',
    ],
    aliases: ['hades', 'the realm of the dead', 'the grave', 'haides'],
    relatedTerms: ['sheol', 'intermediate-state', 'gehenna', 'lake-of-fire', 'death'],
    distinctions: [
      'Hades is not Gehenna. They are different words used of different things, and Luke 16 uses the former.',
      'Hades is not the lake of fire. Revelation 20:14 has Hades thrown into the lake of fire.',
      'Hades is not the English word hell, which does duty for Sheol, Hades and Gehenna at once.',
      'Hades is not permanent. It gives up its dead at the resurrection and is then destroyed.',
      'Torment in Hades is not evidence about the final state, because Hades precedes the judgment.',
    ],
    principalPassages: [
      'Luke 16:19-31',
      'Revelation 20:13-14',
      'Acts 2:27-31',
      'Matthew 16:18',
      'Revelation 1:18',
    ],
    relatedSections: ['S05', 'S09', 'S03'],
    relatedObjections: ['S33'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [
      'How much of the rich man and Lazarus account is narrative detail and how much is parabolic furniture.',
    ],
  },
  {
    id: 'sheol',
    slug: 'sheol',
    title: 'Sheol',
    definition:
      'The Hebrew word for the realm of the dead in the Old Testament. Both the righteous and the wicked are said to go there, and English versions render it grave, pit and hell inconsistently.',
    body: [
      'Sheol is where the dead are. Jacob expects to go down to Sheol mourning for his son. Job asks to be hidden there. The Psalms both fear it and hope for rescue from it. It is not presented as the destination of the wicked alone, and it is not the sentence handed down at the last judgment.',
      'The Greek Old Testament usually renders Sheol as Hades, which is how the two terms come to overlap in New Testament usage. Reading Hades correctly therefore depends on reading Sheol correctly first.',
      'What Sheol is not: it is not Gehenna, which belongs to the Gospels and to final judgment; it is not the lake of fire, which is an image in Revelation; and it is not a synonym for the English word hell. A version that renders Sheol as hell in one verse and grave in the next has made an interpretive decision on the reader’s behalf.',
    ],
    aliases: ['sheol', 'the pit', 'the grave'],
    relatedTerms: ['hades', 'intermediate-state', 'death', 'gehenna'],
    distinctions: [
      'Sheol receives the righteous as well as the wicked, which no doctrine of hell allows.',
      'Sheol is not Gehenna. The words belong to different languages, Testaments and topics.',
      'Sheol is not the lake of fire, an image that appears only in Revelation.',
      'Rendering Sheol as hell imports a later meaning the Hebrew text does not carry.',
    ],
    principalPassages: [
      'Genesis 37:35',
      'Job 14:13',
      'Psalms 16:10',
      'Psalms 49:15',
      'Ecclesiastes 9:10',
    ],
    relatedSections: ['S05', 'S09'],
    relatedObjections: [],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [
      'Whether the Old Testament expects conscious existence in Sheol, which its texts describe in varied ways.',
    ],
  },
  {
    id: 'gehenna',
    slug: 'gehenna',
    title: 'Gehenna',
    definition:
      'The word Jesus uses for the place of final destruction. It transliterates the name of the Valley of the Son of Hinnom, a ravine outside Jerusalem with a history of child sacrifice and slaughter.',
    body: [
      'The valley is named in the Old Testament as the site where children were burned in sacrifice, and Jeremiah announces that it will be renamed the Valley of Slaughter, filled with dead bodies left as food for birds and beasts. That is the background Jesus draws on when he warns about Gehenna.',
      'In the Gospels Gehenna is where body and soul can be destroyed, where it is better to enter life maimed than to be thrown in whole, and where the worm does not die and the fire is not quenched. That last phrase quotes Isaiah, and in Isaiah the objects of the worm and the fire are corpses.',
      'What Gehenna is not: it is not Hades or Sheol, the realm of the dead before the resurrection; it is not the phrase lake of fire, though both describe the same final outcome; and it is not the English word hell, which does duty for several distinct terms at once.',
    ],
    aliases: ['gehenna', 'valley of hinnom', 'valley of the son of hinnom', 'topheth', 'geenna'],
    relatedTerms: ['hades', 'sheol', 'lake-of-fire', 'fire', 'destruction'],
    distinctions: [
      'Gehenna is not Hades. Luke 16 uses Hades of the rich man, and never uses Gehenna.',
      'The Greek word appears in the Synoptic Gospels and in James, and not in the Old Testament.',
      'Gehenna is not called the lake of fire, although both name the end of the unrighteous.',
      'The claim that Gehenna was a burning rubbish dump in the first century lacks primary evidence and is not asserted here.',
    ],
    principalPassages: [
      'Matthew 10:28',
      'Mark 9:42-48',
      'Matthew 5:29-30',
      'Jeremiah 7:31-33',
      'James 3:6',
    ],
    relatedSections: ['S15', 'S10', 'S01', 'S05'],
    relatedObjections: [],
    sourceIds: ['dear-bible-teaches-annihilationism', 'rethinking-hell-worm-does-not-die'],
    openQuestions: [
      'What first-century hearers pictured on hearing Gehenna, which the surviving sources do not settle.',
    ],
  },
  {
    id: 'lake-of-fire',
    slug: 'lake-of-fire',
    title: 'The Lake of Fire',
    definition:
      'The image in Revelation for the final destiny of the devil, the beast, the false prophet, Death, Hades, and those whose names are not written in the book of life. Revelation calls it the second death.',
    body: [
      'The lake of fire appears only in Revelation, inside a vision full of symbolic images. It receives the beast and the false prophet, then the devil, then Death and Hades, and finally anyone not found written in the book of life. Matthew 25 says the eternal fire was prepared for the devil and his angels.',
      'The clause about torment day and night for ever and ever stands in verse 10, where only three figures are in view. When Death and Hades are thrown in, the text does not repeat it. It says instead that this is the second death. An argument from that placement is suggestive rather than decisive, and this site presents it on those terms.',
      'What the lake of fire is not: it is not Hades, which is thrown into it; it is not Sheol, a Hebrew word from a different Testament; and it is not the general English word hell. It is a particular image whose meaning Revelation states in its own words.',
    ],
    aliases: [
      'lake that burns with fire and sulfur',
      'lake of burning sulphur',
      'the fiery lake',
      'the second death',
    ],
    relatedTerms: ['second-death', 'gehenna', 'hades', 'fire', 'final-judgment'],
    distinctions: [
      'The lake of fire is not Hades, since Revelation has Hades thrown into it.',
      'The lake of fire is not the intermediate state, which precedes the resurrection entirely.',
      'Revelation names it the second death, which is the book’s own interpretation of the image.',
      'Matthew 25:41 says the eternal fire was prepared for the devil and his angels, not for human beings.',
    ],
    principalPassages: [
      'Revelation 20:10-15',
      'Revelation 21:8',
      'Revelation 19:20',
      'Matthew 25:41',
    ],
    relatedSections: ['S03', 'S13', 'S20', 'S02'],
    relatedObjections: ['S28', 'S30', 'S32'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [
      'Whether the lake of fire is a literal place or a symbol within a symbolic vision.',
      'Whether the beast and the false prophet are human figures or spiritual entities, on which conditionalists differ.',
    ],
  },
  {
    id: 'tree-of-life',
    slug: 'tree-of-life',
    title: 'The Tree of Life',
    definition:
      'The tree in the garden of Eden and in the New Jerusalem. Genesis links eating from it with living for ever, and Revelation places it inside the city with the unrighteous excluded.',
    body: [
      'God barred the way to the tree and gave the reason in plain terms: lest the man reach out his hand, take also of the tree of life, eat, and live for ever. Whatever else the tree signifies, Genesis connects it with continued life and not only with the quality of life.',
      'The tree reappears at the end of Revelation, standing in the city, its leaves for the healing of the nations. Those who wash their robes have the right to it and enter by the gates. Those outside are named, and they are excluded from the tree and from the city alike.',
      'That resurrected bodies go on receiving life through the tree is an inference rather than a statement of Scripture, and this site labels it as one. The argument from exclusion does not depend on it.',
    ],
    aliases: ['tree of life', 'the tree in the garden'],
    relatedTerms: ['immortality', 'eternal-life', 'conditional-immortality', 'death'],
    distinctions: [
      'Exclusion from the tree and exclusion from blessing are different claims, and Genesis states the former.',
      'The tree may be an image rather than a literal tree, and the argument does not turn on which.',
      'Access to the tree is described as a right granted, not a property anyone holds by nature.',
    ],
    principalPassages: [
      'Genesis 2:9',
      'Genesis 3:22-24',
      'Revelation 22:1-5',
      'Revelation 22:14-15',
      'Revelation 2:7',
    ],
    relatedSections: ['S21', 'RB2', 'S22'],
    relatedObjections: ['S28'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [
      'Whether the tree is a means of sustaining life or a sign of the life God gives.',
    ],
  },
  {
    id: 'intermediate-state',
    slug: 'intermediate-state',
    title: 'The Intermediate State',
    definition:
      'The condition of the dead between death and the resurrection. Scripture says less about it than readers often assume, and it is nobody’s final state.',
    body: [
      'The rich man is in Hades in torment while his brothers are still alive, which places that scene in the intermediate state rather than after the last judgment. Peter writes that the Lord knows how to keep the unrighteous under punishment until the day of judgment, which gives both a reason for their continuance and a limit on it.',
      'Conditionalists differ about what this state involves. Some hold that the dead are conscious; some hold that they sleep until the resurrection. Nothing in the case for conditional immortality requires settling that question, and this site does not settle it.',
      'What matters for the argument is that survival here is credited to God sustaining rather than to a soul that cannot die, and that whatever is true of this state is not evidence about the state that follows the judgment.',
    ],
    aliases: [
      'the intermediate state',
      'life between death and resurrection',
      'the state of the dead',
    ],
    relatedTerms: ['hades', 'sheol', 'resurrection', 'death', 'second-death'],
    distinctions: [
      'The intermediate state is not the final state, and evidence about one is not evidence about the other.',
      'Being sustained until judgment is not the same as being immortal by nature.',
      'Hades names the realm and the intermediate state names the period; the two are related but not identical.',
    ],
    principalPassages: [
      'Luke 16:19-31',
      '2 Peter 2:9',
      'Philippians 1:23',
      'Ecclesiastes 9:5',
      'Revelation 6:9-11',
    ],
    relatedSections: ['S05', 'S09', 'S06'],
    relatedObjections: ['S33'],
    sourceIds: ['dear-bible-teaches-annihilationism', 'irenaeus-against-heresies'],
    openQuestions: [
      'Whether the dead are conscious before the resurrection, on which conditionalists genuinely differ.',
      'Whether the rich man and Lazarus is meant to describe this state or to make a different point entirely.',
    ],
  },
  {
    id: 'body-soul-and-spirit',
    slug: 'body-soul-and-spirit',
    title: 'Body, Soul and Spirit',
    definition:
      'The biblical vocabulary for the parts or aspects of a human being. Christians divide over whether a person is two parts or three, and the case for conditional immortality does not depend on the answer.',
    body: [
      'Some hold that a person is body and soul, with spirit another word for the same immaterial aspect. Others hold that body, soul and spirit are distinguishable, with the spirit naming what relates to God and is made alive in Christ. Scripture uses the words in ways that have supported both readings for centuries.',
      'Matthew 10:28 is the text that matters most here, because it ties the fate of body and soul together instead of separating them. Jesus says God is able to destroy both in Gehenna, and he says it in direct comparison with those who can kill the body only.',
      'This site sets out both anthropologies and assumes neither. What the argument needs is the link Jesus draws between the two, not a verdict on how many parts a person has.',
    ],
    aliases: ['dichotomy', 'trichotomy', 'biblical anthropology', 'soul and spirit', 'nephesh'],
    relatedTerms: ['death', 'immortality', 'resurrection', 'second-death', 'destruction'],
    distinctions: [
      'The soul in Hebrew usage often means the living person, not an immaterial part that survives it.',
      'Two-part and three-part views are held by conditionalists and by traditionalists alike.',
      'Saying the soul can be destroyed is not the same as saying human beings are merely physical.',
    ],
    principalPassages: [
      'Matthew 10:28',
      '1 Thessalonians 5:23',
      'Genesis 2:7',
      'Hebrews 4:12',
      'James 2:26',
    ],
    relatedSections: ['S10', 'RB2', 'S18', 'S22'],
    relatedObjections: ['S31'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [
      'Which anthropology best fits the biblical usage, which this site does not attempt to settle.',
    ],
  },
  {
    id: 'sodom-and-gomorrah',
    slug: 'sodom-and-gomorrah',
    title: 'Sodom and Gomorrah',
    definition:
      'The cities destroyed in Genesis 19, which Peter names as an example of what is coming for the ungodly and which Jude describes as undergoing a punishment of eternal fire.',
    body: [
      'Peter selects two features when he calls the cities an example: they were turned to ashes, and they were condemned to extinction. Both are observable facts about what happened, and neither belongs to a picture of unending conscious torment.',
      'Abraham looked out the next morning and saw smoke rising from the plain. The fire had finished its work within a day, and the cities were never rebuilt. Jude’s phrase about eternal fire describes a fire whose effect is permanent, not one that is still burning.',
      'Some interpreters answer that the example Peter has in view is not the physical destruction but what the inhabitants went on to experience. That reading sets aside the very features Peter names, and Jesus says it will be more bearable for Sodom on the day of judgment than for some other towns, which shows their judgment is still ahead of them.',
    ],
    aliases: ['sodom', 'gomorrah', 'the cities of the plain'],
    relatedTerms: [
      'fire',
      'destruction',
      'eternal-and-everlasting',
      'day-of-the-lord',
      'final-judgment',
    ],
    distinctions: [
      'Eternal fire in Jude describes permanence of effect, not a fire that still burns.',
      'The example concerns the destruction of the cities, not what their inhabitants experience now.',
      'That the inhabitants suffered during the judgment is not in dispute; the texts simply do not dwell on it.',
    ],
    principalPassages: [
      '2 Peter 2:6',
      'Jude 7',
      'Genesis 19:24-28',
      'Matthew 10:15',
      'Ezekiel 16:49-50',
    ],
    relatedSections: ['S14', 'S13', 'S15', 'S23'],
    relatedObjections: [],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [
      'What the inhabitants of Sodom are experiencing now, which Scripture does not describe.',
    ],
  },
  {
    id: 'day-of-the-lord',
    slug: 'day-of-the-lord',
    title: 'The Day of the Lord',
    definition:
      'The prophetic and apostolic language for the day when God acts decisively in judgment and salvation. The New Testament ties the last judgment and the destruction of the ungodly to that day.',
    body: [
      'The prophets describe the day of the Lord as a day of wrath, distress, darkness and a full and sudden end. Peter writes that the present heavens and earth are kept until the day of judgment and destruction of the ungodly, which sets the verdict and the outcome on one occasion.',
      'Jesus can say that the day of judgment will be more bearable for Sodom than for a town that rejected his messengers. That comparison treats the day itself as the thing whose severity varies, which reads awkwardly if the day is only the entrance to a sentence still being served.',
      'The word day does not by itself fix a duration. Scripture uses it flexibly, and this site makes no claim about how long the day lasts.',
    ],
    aliases: ['day of the Lord', 'day of wrath', 'day of judgment', 'that day'],
    relatedTerms: ['final-judgment', 'punishment', 'destruction', 'resurrection', 'fire'],
    distinctions: [
      'The day of the Lord and the final judgment overlap in the New Testament, but the phrase is broader in the prophets.',
      'Naming a day does not settle how long that day is.',
      'Prophetic days of the Lord within history are patterns for the last one, not the same event.',
    ],
    principalPassages: [
      'Zephaniah 1:15-18',
      '2 Peter 3:7-13',
      'Romans 2:5',
      'Matthew 10:15',
      '1 Thessalonians 5:2-3',
    ],
    relatedSections: ['S23', 'S09', 'S15', 'S08'],
    relatedObjections: ['S30'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [
      'How the prophetic day of the Lord relates to the final judgment in every passage that uses it.',
    ],
  },
  {
    id: 'weeping-and-gnashing-of-teeth',
    slug: 'weeping-and-gnashing-of-teeth',
    title: 'Weeping and Gnashing of Teeth',
    definition:
      'The phrase Jesus uses in several parables for the response of those shut out. Weeping conveys grief elsewhere in Scripture, and gnashing of teeth conveys anger.',
    body: [
      'The phrase appears in parables with a fiery furnace and in parables with no fire at all, which points to a response at the moment of exclusion rather than to the experience of burning. In Luke the only place described is the house, and those outside are simply not admitted.',
      'Gnashing of teeth elsewhere in Scripture signals rage. Job speaks of an adversary gnashing at him, the Psalms use it of enemies, and the council gnashed their teeth at Stephen. Weeping is the ordinary word for grief and lamentation.',
      'No text says that the weeping and gnashing continues for ever. Conditionalism affirms that the response is real and conscious, and even if the phrase does describe pain rather than grief and anger, that is consistent with a judgment severe in every dimension.',
    ],
    aliases: ['gnashing of teeth', 'weeping and gnashing', 'wailing and gnashing of teeth'],
    relatedTerms: ['outer-darkness', 'final-judgment', 'punishment', 'fire'],
    distinctions: [
      'A conscious response at the judgment is not the same as a conscious state without end.',
      'The phrase describes people being cast out; it is not a description of a place.',
      'It occurs with fire and without fire, so it is not a description of burning.',
    ],
    principalPassages: [
      'Matthew 13:41-42',
      'Matthew 22:13',
      'Matthew 25:30',
      'Luke 13:28',
      'Psalms 112:10',
    ],
    relatedSections: ['S06', 'S03', 'S23'],
    relatedObjections: ['S30'],
    sourceIds: ['rethinking-hell-weeping-gnashing', 'dear-bible-teaches-annihilationism'],
    openQuestions: ['Whether the phrase can refer to a period after the judgment scene itself.'],
  },
  {
    id: 'outer-darkness',
    slug: 'outer-darkness',
    title: 'Outer Darkness',
    definition:
      'The phrase in three of Matthew’s parables for the place outside the feast, the wedding hall and the master’s house, where those who are excluded are thrown.',
    body: [
      'In each case the setting is a household scene: a banquet, a wedding, a settling of accounts. The one excluded is bound and cast outside, away from light, warmth and provision. The image is exclusion from where life is, not a description of a furnace.',
      'Jude and 2 Peter use similar darkness language, and 2 Peter connects it with angels kept until the judgment. In those texts the imagery belongs to the period before the final reckoning rather than after it.',
      'Being thrown outside, bound, and away from the source of light and sustenance does not suggest long survival. The phrase carries real horror without implying that those cast out continue there without end.',
    ],
    aliases: ['outer darkness', 'the darkness outside', 'blackest darkness'],
    relatedTerms: ['weeping-and-gnashing-of-teeth', 'final-judgment', 'punishment', 'gehenna'],
    distinctions: [
      'Outer darkness is not Gehenna, and Matthew uses the two phrases in different settings.',
      'Darkness in Jude and 2 Peter is language of exclusion and detention rather than of fire.',
      'Darkness and fire are different images, and pressing both literally at once produces an odd picture.',
    ],
    principalPassages: [
      'Matthew 8:12',
      'Matthew 22:13',
      'Matthew 25:30',
      'Jude 13',
      '2 Peter 2:17',
    ],
    relatedSections: ['S06', 'S23'],
    relatedObjections: ['S30'],
    sourceIds: ['rethinking-hell-weeping-gnashing', 'dear-bible-teaches-annihilationism'],
    openQuestions: [
      'Whether reserved for ever in Jude 13 attaches to the reserving or to the darkness itself.',
    ],
  },
  {
    id: 'image-of-god',
    slug: 'image-of-god',
    title: 'The image of God',
    definition:
      'The biblical claim that human beings are made in God’s image and likeness, and so represent and reflect him in creation in a way no other earthly creature does.',
    body: [
      'Genesis states that God made humanity in his own image, and the New Testament treats that status as the ground of human dignity. The question this site has to answer is a narrower one: does bearing the image entail that a human being cannot cease to exist?',
      'Scripture never defines the image as inherent immortality. Human beings are not omniscient, omnipresent or omnipotent, and no one argues that the image confers those. The same Scriptures that describe the image also describe human life as grass, as breath, and as a mist that appears for a little while.',
      'Two arguments on this site turn on the distinction. RB2 asks whether the image makes the soul indestructible, and answers that immortality is attributed to God and given through Christ rather than possessed by nature. S31 takes the pastoral form of the objection, that God would not destroy the crown of his creation, and grants the premise while denying that the conclusion follows.',
    ],
    aliases: [
      'imago dei',
      'image bearer',
      'image bearers',
      'made in gods image',
      'likeness of god',
    ],
    relatedTerms: [
      'immortality',
      'conditional-immortality',
      'body-soul-and-spirit',
      'resurrection',
    ],
    distinctions: [
      'The image of God is not the same as immortality. Scripture attributes immortality to God alone and describes it as a gift given through Christ.',
      'Bearing the image is not the same as being righteous. The image remains in fallen human beings who are nonetheless described as lost in sin.',
      'Representing God is not the same as sharing his incommunicable attributes, such as omniscience or omnipresence.',
    ],
    principalPassages: [
      'Genesis 1:26-27',
      '1 Corinthians 11:7',
      'Romans 3:23',
      '2 Corinthians 3:18',
      'Colossians 1:15',
    ],
    relatedSections: ['RB2', 'S31', 'S22'],
    relatedObjections: ['S31'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    openQuestions: [
      'Whether the image of God is best understood as a status, a capacity, a function, or a relationship. This site does not need to settle that to answer the immortality question.',
    ],
  },
]
