#!/usr/bin/env bun
/**
 * Every repository path the documentation names must be tracked in git.
 *
 * Prose is not compiled, so a documented command can rot into a file that no
 * longer exists — including the runtime error messages that tell an author what
 * to run. Any repo-relative path with a file extension, in Markdown or a
 * TypeScript comment or string, has to resolve.
 *
 * Tracked rather than merely present on disk: a gitignored file exists on the
 * machine that wrote it and in no clone.
 */
import { readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const REPO_ROOT = resolve(import.meta.dir, '..', '..')

/** Top-level directories a real repository path starts with. */
const ROOTS = ['apps/', 'packages/', 'scripts/', 'docs/', 'private/', '.github/', '.claude/']

/**
 * Paths that look like repository files but are not, and never will be.
 *
 * Each one is a genuine reference to something outside the repository or
 * generated into it, so requiring it to exist would be wrong.
 */
const NOT_REPOSITORY_FILES = new Set([
  // Generated by `next build` into a gitignored directory.
  'apps/conditional-immortality/.next/types/routes.d.ts',
  'apps/conditional-immortality/.next/dev/types/routes.d.ts',
])

/** A path mention: a repo-rooted path ending in a file extension. */
const PATH_PATTERN = new RegExp(
  `(?:${ROOTS.map(root => root.replace(/[.]/g, '\\.')).join('|')})` +
    '[A-Za-z0-9_./-]*\\.[A-Za-z0-9]{1,5}',
  'g',
)

function tracked(): string[] {
  const result = Bun.spawnSync(['git', 'ls-files', '-z'], { cwd: REPO_ROOT, stdout: 'pipe' })
  if (result.exitCode !== 0) {
    console.error('`git ls-files` failed, so nothing could be checked.')
    process.exit(1)
  }
  return new TextDecoder()
    .decode(result.stdout)
    .split('\0')
    .filter(entry => entry.length > 0)
}

const SEARCHED_EXTENSIONS = ['.md', '.ts', '.tsx', '.json', '.yml', '.yaml']

/** Config files that carry no extension, matched by name. */
const SEARCHED_NAMES = ['.gitignore', '.gitattributes', '.npmrc', 'Dockerfile']

/** Files whose non-comment lines are patterns, not prose. */
const IGNORE_FILES = ['.gitignore', '.gitattributes']

function isSearched(entry: string): boolean {
  if (SEARCHED_EXTENSIONS.some(extension => entry.endsWith(extension))) return true
  const name = entry.split('/').pop() ?? ''
  return SEARCHED_NAMES.includes(name)
}

interface Missing {
  readonly file: string
  readonly line: number
  readonly path: string
}

const trackedPaths = new Set(tracked())
const missing: Missing[] = []
let filesSearched = 0
let mentions = 0

for (const entry of trackedPaths) {
  if (!isSearched(entry)) continue

  const content = readFileSync(join(REPO_ROOT, entry), 'utf8')
  filesSearched += 1

  // In an ignore file only the comments are prose; a pattern names an untracked
  // path by definition.
  const commentsOnly = IGNORE_FILES.includes(entry.split('/').pop() ?? '')

  const lines = content.split(/\r?\n/)
  for (const [index, line] of lines.entries()) {
    if (commentsOnly && !line.trimStart().startsWith('#')) continue
    for (const match of line.matchAll(PATH_PATTERN)) {
      const candidate = match[0].replace(/[.,;:)]+$/, '')
      mentions += 1
      if (NOT_REPOSITORY_FILES.has(candidate)) continue
      if (trackedPaths.has(candidate)) continue
      missing.push({ file: entry, line: index + 1, path: candidate })
    }
  }
}

console.log('Documentation path check')
console.log('========================')
console.log(`  files searched ${filesSearched}`)
console.log(`  path mentions  ${mentions}`)
console.log('')

if (filesSearched === 0) {
  console.error('No files were searched, which cannot be right. Refusing to report success.')
  process.exit(1)
}

if (missing.length > 0) {
  console.error(`${missing.length} reference(s) to files that do not exist:`)
  for (const entry of missing) {
    console.error(`  x ${entry.file}:${entry.line}`)
    console.error(`      ${entry.path}`)
  }
  console.error('')
  console.error('Either create the file or correct the reference. A documented command that')
  console.error('does not exist is worse than no documentation.')
  process.exit(1)
}

console.log(`Every one of the ${mentions} path mentions resolves.`)
