import type { CaseSection } from '@ci/content-schema'

/**
 * The permanent section registry.
 *
 * These identifiers never change. Slugs, titles and routes may be revised;
 * `id` is the stable identity used by the changelog, reading progress, search,
 * the migration ledger and every cross-reference in the content.
 *
 * `originalPages` are estimates. The DOCX stores no hard page boundaries, so
 * pages are derived from paragraph position across the 997-paragraph body and
 * are labelled as approximate wherever they are shown to a reader.
 *
 * Ordering note: the source document's table of contents lists physical death
 * before Jesus' death, while the body headings number them the other way. The
 * body headings are canonical here (S17 = Jesus' death, S18 = physical death),
 * and the discrepancy is recorded in the migration ledger.
 */
export const CASE_SECTIONS: readonly CaseSection[] = [
  {
    id: 'P00',
    canonicalOrder: 0,
    group: 'preface',
    slug: 'why-this-matters',
    route: '/case/why-this-matters/',
    title: 'Why This Question Matters',
    question: 'Why is it worth working out what final punishment actually is?',
    thesis:
      'Nothing in this section is evidence that conditional immortality is true. It sets out why the question is worth answering carefully: what we believe about final punishment shapes what we say about God, how we grieve, and how we evangelise.',
    shortSummary:
      'The reasons the question matters, stated plainly, with an explicit warning that the usefulness of a doctrine is never an argument for its truth.',
    evidenceRole: 'further-consideration',
    reviewStatus: 'reviewed',
    originalPages: [8, 9, 10],
    sourceParagraphIds: ['p146', 'p147', 'p188'],
    primaryPassages: ['Matthew 7:13-14', '2 Corinthians 5:10'],
    relatedPassages: ['Ezekiel 33:11'],
    relatedSections: ['S29', 'S19', 'APP1'],
    topicIds: ['eternal-conscious-torment', 'conditional-immortality', 'universal-reconciliation'],
    sourceIds: ['welch-source-document', 'sprinkle-introduction'],
    establishes: [
      'The debate concerns the nature of final punishment, not whether judgment is real.',
      'A mistaken view of punishment distorts what we say about the character of God.',
      'Reactions against eternal conscious torment can produce doctrines Scripture does not teach.',
    ],
    doesNotEstablish: [
      'That conditional immortality is true. No pastoral benefit is evidence for a doctrine.',
      'That eternal conscious torment is held for bad motives, or that its defenders are uncaring.',
    ],
    caveats: [
      'The author states directly that perceived benefits of a doctrine are not support for it.',
    ],
    aliases: ['preface', 'why does this matter', 'p00'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'RB1',
    canonicalOrder: 1,
    group: 'roadblock',
    slug: 'tradition',
    route: '/case/roadblocks/tradition/',
    title: 'Is Conditional Immortality a New Teaching?',
    question: 'Has eternal conscious torment always been the traditional view?',
    thesis:
      'Conditional immortality is not a modern invention. Several early Christian writers describe the end of the unrighteous in terms of loss of life rather than unending torment, and eternal conscious torment did not become dominant in the West until considerably later.',
    shortSummary:
      'What the earliest Christian writings actually say about the fate of the wicked, how confident we can be about each one, and why antiquity settles nothing on its own.',
    evidenceRole: 'historical-linguistic',
    reviewStatus: 'specialist-review-pending',
    originalPages: [10, 11, 12, 13, 14, 15],
    sourceParagraphIds: ['p191', 'p192', 'p193', 'p199', 'p200', 'p201', 'p207'],
    primaryPassages: [],
    relatedPassages: [],
    relatedSections: ['RB2', 'S22'],
    topicIds: ['conditional-immortality', 'annihilationism', 'eternal-conscious-torment'],
    sourceIds: [
      'irenaeus-against-heresies',
      'ignatius-magnesians',
      'augustine-enchiridion',
      'dear-bible-teaches-annihilationism',
      'rethinking-hell-early-church',
      'truth-according-to-scripture-apostolic-fathers',
      'church-fathers-conditionalists-video',
      'history-in-the-bible-fathers',
    ],
    ectPosition:
      'Defenders of eternal conscious torment point out that it has been the settled majority position of the Western church for roughly sixteen centuries, that it is affirmed in historic confessions, and that a doctrine held so widely for so long should not be overturned on the strength of a handful of contested early texts.',
    conditionalistResponse:
      'The claim here is narrow: conditionalism is not novel, and several early writers speak of the end of the unrighteous as the loss of continued existence. That establishes that the position deserves examination, and nothing more. Antiquity is not truth.',
    establishes: [
      'Conditional immortality was held by identifiable early Christian writers.',
      'Eternal conscious torment was not the uncontested position of the earliest centuries.',
      'Augustine himself records that many people in his day rejected eternal torment.',
    ],
    doesNotEstablish: [
      'That conditional immortality is true, since the antiquity of a view does not make it correct.',
      'That conditionalism was demonstrably the counted majority view before AD 300.',
    ],
    caveats: [
      'The source document says conditionalism was "apparently the majority view" until at least AD 300. The surviving corpus is too small and too indirect to support a counted majority claim, and this page states the narrower conclusion the evidence supports.',
      'Several figures listed in the original document leave no clear statement on final punishment at all. Those are marked indeterminate rather than being assigned to a side.',
    ],
    aliases: ['rb1', 'roadblock 1', 'tradition', 'early church', 'church fathers'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'RB2',
    canonicalOrder: 2,
    group: 'roadblock',
    slug: 'image-of-god',
    route: '/case/roadblocks/image-of-god/',
    title: 'Does the Image of God Make Humans Immortal?',
    question: 'Does bearing God’s image mean the soul cannot die?',
    thesis:
      'Bearing the image of God means human beings reflect God in creaturely measure. It does not mean they share his incommunicable attributes. Scripture treats human life as fragile and dependent, and names immortality as something God alone possesses and gives.',
    shortSummary:
      'Why the image of God does not entail an indestructible soul, and where Scripture locates immortality instead.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'reviewed',
    originalPages: [15, 16],
    sourceParagraphIds: ['p279', 'p280', 'p296', 'p299', 'p302'],
    primaryPassages: [
      '1 Timothy 6:15-16',
      '2 Timothy 1:10',
      'Romans 2:7',
      '1 Corinthians 15:42-43',
    ],
    relatedPassages: [
      '1 Peter 1:23-24',
      'Psalms 144:4',
      'Isaiah 40:6-8',
      'James 4:14',
      'John 6:51',
      'Ecclesiastes 3:11',
      'Genesis 3:4',
    ],
    relatedSections: ['S21', 'S22', 'RB1'],
    topicIds: ['immortality', 'image-of-god', 'conditional-immortality', 'body-soul-and-spirit'],
    sourceIds: ['dear-bible-teaches-annihilationism', 'afterlife-god-alone-is-immortal'],
    ectPosition:
      'Many defenders of eternal conscious torment hold that human beings, uniquely among earthly creatures, are made for endless existence, and that this follows from being made in God’s image. On that view the question is never whether a person continues, only where.',
    conditionalistResponse:
      'The image of God is never defined in Scripture as inherent immortality. Human beings are not omniscient, omnipresent or omnipotent, and the same texts that describe the image also describe human life as grass, breath and vapour. Immortality is explicitly said to belong to God and to be given through Christ.',
    establishes: [
      'Scripture nowhere states that the image of God confers inherent immortality.',
      'Immortality is attributed to God alone and is described as a gift brought to light in Christ.',
      'Human existence is repeatedly described as dependent and perishable.',
    ],
    doesNotEstablish: [
      'That human beings are merely physical, or that the intermediate state is unconscious.',
      'The precise mechanics of how God sustains the unrighteous until judgment.',
    ],
    caveats: [
      'The historical claim that inherent immortality of the soul entered Christian thought from Plato is more complicated than a single line of influence. This page separates the biblical claim from the historical one and treats them independently.',
    ],
    aliases: ['rb2', 'roadblock 2', 'image of god', 'imago dei', 'immortal soul'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'RB3',
    canonicalOrder: 3,
    group: 'roadblock',
    slug: 'infinite-punishment',
    route: '/case/roadblocks/infinite-punishment/',
    title: 'Does Sin Against an Infinite God Require Infinite Punishment?',
    question: 'Does the greatness of the one sinned against set the size of the penalty?',
    thesis:
      'The argument that sin against an infinite God requires infinite punishment is a theological inference rather than a biblical statement, and Scripture repeatedly grades punishment by the knowledge and circumstance of the sinner rather than by the dignity of the one sinned against.',
    shortSummary:
      'The infinite-offence argument stated fairly from its own defenders, then weighed against the texts where Scripture actually calibrates degrees of judgment.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'source-checked',
    originalPages: [16, 17, 18, 19, 20],
    sourceParagraphIds: ['p304', 'p305', 'p306', 'p312', 'p345', 'p354', 'p357', 'p359', 'p370'],
    primaryPassages: ['Luke 12:47-48', 'Matthew 11:20-24', 'Romans 2:12', 'James 4:17'],
    relatedPassages: [
      'Luke 23:34',
      'John 15:22',
      'John 9:41',
      'Romans 5:13',
      '1 Timothy 1:13',
      '1 Corinthians 13:12',
      'Mark 3:28-30',
      '2 Corinthians 5:10',
    ],
    relatedSections: ['S04', 'S23', 'S26', 'S32'],
    topicIds: ['punishment', 'final-judgment', 'eternal-conscious-torment'],
    sourceIds: [
      'aquinas-summa-1a2ae-87',
      'edwards-justice-of-god',
      'macarthur-truth-about-hell',
      'rethinking-hell-finite-sins',
      'dear-bible-teaches-annihilationism',
    ],
    ectPosition:
      'On the traditional argument, the gravity of an offence rises with the dignity of the person offended, God is of infinite dignity, and therefore sin against God incurs a penalty no finite creature can discharge. Endless punishment follows, not from cruelty, but from the infinite worth of the one sinned against.',
    conditionalistResponse:
      'Scripture grades punishment by what the sinner knew and could have known. Fewer blows and more blows, more bearable and less bearable, guilt incurred and guilt withheld: these distinctions run against a penalty fixed by the dignity of the offended party alone. And a punishment of infinite magnitude, paid out at finite intensity, is never actually completed.',
    establishes: [
      'The infinite-punishment argument is offered by its own defenders as reasoning about God, not as exegesis.',
      'Scripture repeatedly calibrates judgment by the sinner’s knowledge and circumstance.',
      'On the traditional view, full justice for a given sin is never reached at any moment.',
    ],
    doesNotEstablish: [
      'That final punishment is mild, brief, or anything less than the full measure God determines.',
      'That every defender of eternal conscious torment relies on the infinite-offence argument.',
    ],
    caveats: [
      'The Aquinas passage frequently quoted in support of infinite punishment is stated by Aquinas as an objection he then answers. This page cites it in its actual context.',
      'Objections to eternal conscious torment on grounds of fairness are themselves philosophical, and are not treated here as evidence.',
    ],
    aliases: ['rb3', 'roadblock 3', 'infinite punishment', 'infinite offense', 'aquinas'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S01',
    canonicalOrder: 4,
    group: 'key-text',
    slug: 'mark-9',
    route: '/case/key-texts/mark-9/',
    title: 'Mark 9: Undying Worms and Unquenchable Fire',
    question: 'Does an undying worm and an unquenchable fire require an undying person?',
    thesis:
      'Jesus closes his warning in Mark 9 by quoting the last verse of Isaiah, where the worm and the fire work on corpses. The imagery describes destruction that is not interrupted and not reversed, and neither Isaiah nor Jesus places a conscious sufferer inside it.',
    shortSummary:
      'What Isaiah 66:24 contributes to Jesus’ warning, and what "unquenchable" means everywhere else in Scripture.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'reviewed',
    originalPages: [20, 21],
    sourceParagraphIds: ['p374', 'p375', 'p376', 'p385', 'p392', 'p394'],
    primaryPassages: ['Mark 9:42-48', 'Isaiah 66:24', 'Daniel 12:2'],
    relatedPassages: [
      'Isaiah 66:15-24',
      'Ezekiel 20:47-48',
      'Isaiah 1:31',
      'Jeremiah 4:4',
      'Jeremiah 17:27',
      'Amos 5:6',
    ],
    relatedSections: ['S04', 'S13', 'S12', 'S08'],
    topicIds: ['fire', 'gehenna', 'destruction', 'eternal-and-everlasting'],
    sourceIds: [
      'rethinking-hell-worm-does-not-die',
      'rethinking-hell-fire-not-quenched',
      'dear-bible-teaches-annihilationism',
      'strongs-h2781',
    ],
    ectPosition:
      'Interpreters who hold eternal conscious torment read the undying worm and the unquenchable fire as deliberate images of a punishment without end. On this reading Jesus intensifies Isaiah: the worm that never dies and the fire that is never put out describe a condition that persists, and a persisting punishment implies a persisting person.',
    conditionalistResponse:
      'In Isaiah the objects of the worm and the fire are dead bodies, and the point of both images is completion, not duration. A worm that does not die finishes its work; a fire that is not quenched is a fire nobody puts out before it has consumed what it was burning.',
    establishes: [
      'Mark 9:48 is a direct quotation of Isaiah 66:24, where the objects are corpses.',
      'Unquenchable fire in the Hebrew prophets describes fire that cannot be stopped, not fire that never ends.',
      'Neither text describes the objects of the worm and fire as conscious.',
    ],
    doesNotEstablish: [
      'That the final punishment involves no conscious experience at all.',
      'That every question about Gehenna in the Gospels is settled by this passage.',
    ],
    caveats: [
      'Some translations render the phrase in Mark 9 as fire that never goes out. That rendering is an interpretive choice rather than a literal one, and this page shows the difference rather than assuming it.',
    ],
    aliases: ['s01', 'mark 9', 'undying worm', 'unquenchable fire', 'worm does not die'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S02',
    canonicalOrder: 5,
    group: 'key-text',
    slug: 'revelation-14',
    route: '/case/key-texts/revelation-14/',
    title: 'Revelation 14: The Smoke of Their Torment',
    question: 'What exactly is said to rise for ever and ever?',
    thesis:
      'Revelation 14 says the smoke of their torment rises for ever, not that the torment itself continues for ever. Rising smoke is used elsewhere in Scripture as a standing monument to a destruction that is already complete.',
    shortSummary:
      'The grammar of Revelation 14:11, the Edom and Babylon parallels, and three readings of the phrase about having no rest.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'authors-present-interpretation',
    originalPages: [21, 22],
    sourceParagraphIds: ['p398', 'p399', 'p402', 'p409', 'p412', 'p416'],
    primaryPassages: ['Revelation 14:9-11'],
    relatedPassages: [
      'Isaiah 34:9-10',
      'Revelation 19:3',
      'Revelation 18:21',
      'Revelation 4:8',
      'Genesis 19:28',
    ],
    relatedSections: ['S03', 'S13', 'S14', 'S17'],
    topicIds: ['fire', 'eternal-and-everlasting', 'destruction', 'punishment'],
    sourceIds: ['rethinking-hell-bible-fellowship-church', 'dear-bible-teaches-annihilationism'],
    ectPosition:
      'Interpreters who hold eternal conscious torment read this passage as one of the clearest in Scripture: torment with fire and sulphur, in the presence of the Lamb, with smoke rising for ever and no rest day or night. Taken together these read naturally as a description of unending conscious suffering.',
    conditionalistResponse:
      'The clause that continues for ever attaches to the smoke, and Scripture twice uses smoke rising for ever of places already destroyed. Edom is desolate, not still alight; Babylon has already fallen when the same words are used of her.',
    establishes: [
      'What the text says rises for ever and ever is the smoke, not the tormenting.',
      'Rising smoke functions elsewhere as a memorial of completed destruction.',
      'The passage addresses worshippers of the beast, not the unrighteous in general.',
    ],
    doesNotEstablish: [
      'That the torment described is brief or painless.',
      'Which of the three readings of the phrase about no rest day or night is correct.',
    ],
    caveats: [
      'The reading of the no-rest clause is the author’s own, offered as a suggestion. Three possible readings are set out and none is claimed as settled.',
      'The argument that angels could not be present for an unending torment assumes a particular view of angelic presence, and is presented as an observation rather than a proof.',
    ],
    aliases: [
      's02',
      'revelation 14',
      'smoke of their torment',
      'rev 14:11',
      'no rest day or night',
    ],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S03',
    canonicalOrder: 6,
    group: 'key-text',
    slug: 'lake-of-fire',
    route: '/case/key-texts/lake-of-fire/',
    title: 'Revelation 20: The Lake of Fire and the Second Death',
    question: 'Whose torment continues for ever in Revelation 20?',
    thesis:
      'The statement about torment day and night for ever appears in verse 10, where only the devil, the beast and the false prophet are in view. When the unrighteous are thrown in five verses later, the text names the outcome differently: this is the second death.',
    shortSummary:
      'Where the clause about unending torment sits in the passage, what the lake of fire does to Death and Hades, and how much weight the placement can carry.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'authors-present-interpretation',
    originalPages: [22, 23, 24],
    sourceParagraphIds: ['p420', 'p421', 'p425', 'p435', 'p436', 'p440', 'p442', 'p443', 'p444'],
    primaryPassages: ['Revelation 20:10-15', 'Matthew 25:41', 'Jude 7'],
    relatedPassages: ['Revelation 21:4', 'Revelation 21:8', '2 Peter 2:6', 'Genesis 19:24-28'],
    relatedSections: ['S02', 'S14', 'S20', 'S32', 'S28'],
    topicIds: ['lake-of-fire', 'second-death', 'fire', 'hades'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    ectPosition:
      'Interpreters who hold eternal conscious torment observe that the unrighteous are thrown into the same lake of fire as the devil, the beast and the false prophet, and conclude that they share the fate the passage has just described: torment day and night for ever and ever.',
    conditionalistResponse:
      'The clause is placed in verse 10, before anyone else has been thrown in. When Death and Hades follow, the text does not repeat it; it calls the lake of fire the second death. Naming the unending torment of three figures and then withholding it from those who come after is a meaningful silence.',
    establishes: [
      'The clause about torment for ever and ever is stated of three figures, before the unrighteous are thrown in.',
      'The lake of fire is described as prepared for the devil and his angels.',
      'The lake of fire is named as the second death, and Death itself is destroyed there.',
    ],
    doesNotEstablish: [
      'That the beast and false prophet are certainly non-human figures.',
      'That the lake of fire is a literal rather than a symbolic image.',
      'The duration or intensity of what the unrighteous consciously experience there.',
    ],
    caveats: [
      'The author’s reading of the beast and the false prophet as spiritual entities is his own present interpretation, and he says openly that he finds Revelation difficult here. Other conditionalists read these figures as human and hold that they too are destroyed.',
      'An argument from placement is an argument from silence. It is suggestive rather than decisive, and is presented that way.',
      'A speculative aside in the source document about angels and the experience of time is not reproduced as evidence. It is recorded in the migration ledger.',
    ],
    aliases: ['s03', 'revelation 20', 'lake of fire', 'second death', 'rev 20:10'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S04',
    canonicalOrder: 7,
    group: 'key-text',
    slug: 'eternal-punishment',
    route: '/case/key-texts/eternal-punishment/',
    title: 'What Does “Eternal Punishment” Mean?',
    question: 'Does eternal punishment require an eternally continuing act of punishing?',
    thesis:
      'The conditionalist reading affirms that the punishment is eternal while understanding the punishment itself as irreversible death or destruction, rather than an endlessly continuing act of punishing.',
    shortSummary:
      'Why Matthew 25:46 pairs two permanent outcomes rather than two continuing activities, and what 2 Thessalonians 1:9 says the punishment is.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'specialist-review-pending',
    originalPages: [24, 25, 26, 27],
    sourceParagraphIds: ['p447', 'p448', 'p450', 'p451', 'p455', 'p473', 'p478', 'p488', 'p498'],
    primaryPassages: ['Matthew 25:31-46', '2 Thessalonians 1:5-10'],
    relatedPassages: [
      'Hebrews 5:9',
      'Hebrews 9:12',
      'Hebrews 9:15',
      'Hebrews 6:2',
      'Mark 3:29',
      'John 17:3',
      'John 10:10',
      'Isaiah 66:15',
      'Nahum 1:6',
    ],
    relatedSections: ['S11', 'S07', 'S03', 'S01', 'RB3'],
    topicIds: [
      'eternal-and-everlasting',
      'punishment',
      'eternal-life',
      'destruction',
      'final-judgment',
    ],
    sourceIds: [
      'rethinking-hell-2-thess-1-9-part-1',
      'rethinking-hell-2-thess-1-9-part-2',
      'biblehub-apo-575',
      'dear-bible-teaches-annihilationism',
    ],
    ectPosition:
      'Matthew 25:46 sets eternal punishment in direct parallel with eternal life. Defenders of eternal conscious torment argue that the same adjective must carry the same force in both halves: if the life is consciously enjoyed without end, the punishment must be consciously endured without end, or the parallel collapses.',
    conditionalistResponse:
      'Both halves are eternal, and conditionalism affirms that. The question is what each noun names. Punishment and destruction are nouns of result, not of ongoing activity, and every other eternal thing in the New Testament names something accomplished once whose effect stands for ever.',
    establishes: [
      'The nouns in these verses name results, not continuing activities.',
      'Other eternal things in the New Testament are accomplished once and stand permanently.',
      '2 Thessalonians 1:9 identifies the punishment itself as destruction.',
    ],
    doesNotEstablish: [
      'That the Greek adjective cannot mean everlasting duration. It often does.',
      'The correct rendering of the preposition in 2 Thessalonians 1:9.',
    ],
    caveats: [
      'The suggestion that the preposition in 2 Thessalonians 1:9 identifies the Lord’s presence as the source of destruction is offered by the author as a suggested reading, with explicit hesitancy, and is flagged for specialist language review. Standard translations divide on this verse.',
    ],
    aliases: [
      's04',
      'eternal punishment',
      'matthew 25:46',
      'aionios',
      'everlasting destruction',
      '2 thessalonians 1:9',
    ],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S05',
    canonicalOrder: 8,
    group: 'key-text',
    slug: 'rich-man-and-lazarus',
    route: '/case/key-texts/rich-man-and-lazarus/',
    title: 'The Rich Man and Lazarus',
    question: 'Is the rich man already experiencing final judgment?',
    thesis:
      'The rich man is in Hades while his five brothers are still alive, which places the scene before the resurrection and the last judgment. Whatever it describes, it is not the final state.',
    shortSummary:
      'Why this passage describes the intermediate state rather than final punishment, and why it therefore supports neither view directly.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'reviewed',
    originalPages: [27],
    sourceParagraphIds: ['p502', 'p503', 'p504', 'p505', 'p508'],
    primaryPassages: ['Luke 16:19-31'],
    relatedPassages: ['Revelation 20:13-14'],
    relatedSections: ['S09', 'S06', 'S03', 'S33'],
    topicIds: ['hades', 'intermediate-state', 'sheol', 'gehenna'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    ectPosition:
      'The passage is often cited as direct evidence that the unrighteous suffer consciously after death, in fire, in a fixed state, with no way across. Defenders of eternal conscious torment note that Jesus himself describes the scene, and that he describes conscious agony.',
    conditionalistResponse:
      'Conditionalism agrees that the scene is conscious and that it is grim. It simply observes what the passage itself indicates: the rich man’s brothers are still alive, so this cannot be after the last judgment. The word used is Hades, not Gehenna.',
    establishes: [
      'The scene takes place before the resurrection and the final judgment.',
      'Hades and Gehenna are distinct terms and are not interchangeable here.',
      'Conscious experience in the intermediate state is not evidence about the final state.',
    ],
    doesNotEstablish: [
      'That the passage supports conditional immortality. It is neutral between the views.',
      'Whether the account is a parable or a report of a real person.',
    ],
    caveats: [
      'This page is included because the passage is frequently cited, not because it advances the positive case.',
    ],
    aliases: ['s05', 'rich man and lazarus', 'luke 16', 'hades', 'intermediate state'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S06',
    canonicalOrder: 9,
    group: 'key-text',
    slug: 'weeping-and-gnashing',
    route: '/case/key-texts/weeping-and-gnashing/',
    title: 'Weeping, Gnashing of Teeth, and Outer Darkness',
    question: 'Does weeping and gnashing of teeth describe an unending condition?',
    thesis:
      'Gnashing of teeth signals anger elsewhere in Scripture and weeping signals grief. The phrase describes a response at the judgment scene, and no text says it continues for ever.',
    shortSummary:
      'What the two words mean in their other biblical occurrences, where the phrase is located in each parable, and why it appears with and without fire.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'reviewed',
    originalPages: [27, 28, 29],
    sourceParagraphIds: ['p509', 'p510', 'p516', 'p520', 'p524', 'p527', 'p537', 'p545', 'p553'],
    primaryPassages: ['Matthew 13:24-43', 'Luke 13:22-30', 'Matthew 22:1-14', 'Matthew 25:14-30'],
    relatedPassages: [
      'Job 16:9',
      'Psalms 35:16',
      'Psalms 112:10',
      'Acts 7:54',
      'Matthew 2:18',
      'Acts 20:37',
      'Matthew 8:12',
      'Jude 13',
      '2 Peter 2:17',
    ],
    relatedSections: ['S13', 'S05', 'S23', 'S03'],
    topicIds: ['weeping-and-gnashing-of-teeth', 'outer-darkness', 'final-judgment', 'fire'],
    sourceIds: ['rethinking-hell-weeping-gnashing', 'dear-bible-teaches-annihilationism'],
    ectPosition:
      'Defenders of eternal conscious torment take the phrase as a settled description of the condition of the lost: continuing anguish, in darkness, away from the feast. That a conscious response is described at all is taken to show that the lost remain conscious.',
    conditionalistResponse:
      'The phrase describes a real and conscious response, and conditionalism affirms that. What it does not say is that the response continues without end. The phrase appears in parables with a furnace and in parables with no fire at all, which points to the moment of exclusion rather than to a place.',
    establishes: [
      'Gnashing of teeth conveys anger elsewhere in Scripture, and weeping conveys grief.',
      'The phrase occurs both with and without fire, so it is not a description of burning.',
      'No text says that weeping and gnashing of teeth continues for ever and ever.',
    ],
    doesNotEstablish: [
      'That the response is brief, or that it involves no pain.',
      'That the phrase can never refer to a period after the judgment scene itself.',
    ],
    caveats: [
      'Even if the phrase does describe pain rather than grief and anger, conditionalism accommodates that: the wrath of God at judgment may be severe in every dimension.',
    ],
    aliases: [
      's06',
      'weeping and gnashing',
      'gnashing of teeth',
      'outer darkness',
      'weeping and gnashing of teeth',
    ],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S07',
    canonicalOrder: 10,
    group: 'biblical-language',
    slug: 'sin-and-death',
    route: '/case/biblical-language/sin-and-death/',
    title: 'The Wages of Sin Is Death',
    question: 'What does Scripture name as the penalty for sin?',
    thesis:
      'From Eden onward, the stated penalty for sin is death. Because believers still die physically and unbelievers also die physically, the penalty in view must be the second death rather than the first.',
    shortSummary:
      'The consistent biblical wage of sin, and why death here cannot mean only the death every human being already dies.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'reviewed',
    originalPages: [30],
    sourceParagraphIds: ['p559', 'p560', 'p564', 'p565', 'p569', 'p572'],
    primaryPassages: ['Romans 6:23', 'Genesis 2:17', 'Ezekiel 18:20', 'James 1:15'],
    relatedPassages: ['Proverbs 14:12', 'Revelation 20:14', 'Romans 5:12-21'],
    relatedSections: ['S16', 'S17', 'S18', 'S11', 'S22'],
    topicIds: ['death', 'second-death', 'punishment'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    ectPosition:
      'Defenders of eternal conscious torment generally understand death in these texts as spiritual death, meaning separation from God rather than the end of existence. On that reading the wage of sin is an unending life apart from God rather than the loss of life.',
    conditionalistResponse:
      'Separation is a real component of this death, and conditionalism agrees. But God chose the language of death, and death is a thing every reader already understands by general revelation. Many alternative images were available for describing unending conscious suffering.',
    establishes: [
      'Death is the penalty Scripture names for sin, consistently and from the beginning.',
      'The death in view cannot be only physical death, which believers also undergo.',
      'The final penalty is identified in Revelation as the second death.',
    ],
    doesNotEstablish: [
      'That death excludes any conscious suffering along the way.',
      'That separation is not part of what death means in these texts.',
    ],
    caveats: [
      'If death simply means separation, S18 argues that separation from the source and sustainer of life still leads to the end of life.',
    ],
    aliases: ['s07', 'wages of sin', 'romans 6:23', 'sin and death', 'penalty for sin'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S08',
    canonicalOrder: 11,
    group: 'biblical-language',
    slug: 'destruction',
    route: '/case/biblical-language/destruction/',
    title: 'The Wicked Will Be Destroyed',
    question: 'What language does Scripture actually use for the fate of the wicked?',
    thesis:
      'Across the Psalms, the Prophets, the Gospels and the Epistles, the fate of the wicked is described in the vocabulary of perishing, being consumed, being burned up, vanishing and being destroyed. This is the ordinary language of the Bible on the subject, and it runs in one direction.',
    shortSummary:
      'The weight of the destruction vocabulary taken together, and why redefining it requires the traditional view to be established first from elsewhere.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'reviewed',
    originalPages: [30, 31, 32],
    sourceParagraphIds: ['p573', 'p574', 'p581', 'p586', 'p596', 'p598', 'p600', 'p602'],
    primaryPassages: ['Psalms 37:20', 'Malachi 4:1-3', '2 Peter 3:7-13', 'Philippians 3:18-19'],
    relatedPassages: [
      'Psalms 34:16',
      'Psalms 37:38',
      'Psalms 59:13',
      'Psalms 145:20',
      'Isaiah 1:31',
      'Isaiah 33:12',
      'Obadiah 1:15-18',
      'Nahum 1:6-10',
      'Luke 3:9',
      'Romans 9:22',
      'Philippians 1:28',
      '1 Thessalonians 5:3',
      'James 4:12',
      '2 Peter 2:12',
      'Matthew 7:13-14',
    ],
    relatedSections: ['S11', 'S12', 'S13', 'S10', 'S22'],
    topicIds: ['destruction', 'perishing', 'death'],
    sourceIds: ['dear-bible-teaches-annihilationism', 'bible-gateway'],
    ectPosition:
      'Defenders of eternal conscious torment generally hold that destruction language describes ruin rather than cessation: a thing can be destroyed in the sense of being rendered useless while continuing to exist, as a wrecked building is destroyed but still stands.',
    conditionalistResponse:
      'Ruin is a legitimate sense of the word group. But the texts add finality that ruin does not account for: no root or branch left, consumed until they are no more, as though they had never been, ashes underfoot. And the comparison in 2 Peter is to animals, which nobody supposes are tormented for ever.',
    establishes: [
      'The dominant biblical vocabulary for the end of the wicked is destruction and perishing.',
      'Several texts add explicit language of completeness that mere ruin does not explain.',
      'The same word for destroy is used of the wicked and of irrational animals.',
    ],
    doesNotEstablish: [
      'That every occurrence of destroy must mean cessation of existence.',
      'That no conscious suffering precedes the destruction.',
    ],
    caveats: [
      'That ashes remain does not require that every particle of a person be removed from the universe. The claim is about conscious existence, not about matter.',
    ],
    aliases: ['s08', 'destroyed', 'destruction', 'perish', 'the wicked will be destroyed'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S09',
    canonicalOrder: 12,
    group: 'biblical-language',
    slug: 'delayed-judgment',
    route: '/case/biblical-language/delayed-judgment/',
    title: 'Why Final Judgment Is Delayed',
    question: 'If the wage of sin is death, why are the wicked still here?',
    thesis:
      'God sustains the unrighteous, in this life and in the intermediate state, because there is still a plan of redemption running. Scripture describes them as kept until the day of judgment, which is a reason for their continuance and also a limit on it.',
    shortSummary:
      'Why continued existence before judgment is evidence of God sustaining, not of inherent immortality.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'reviewed',
    originalPages: [32],
    sourceParagraphIds: ['p605', 'p606', 'p607', 'p608', 'p609'],
    primaryPassages: ['2 Peter 2:9', '2 Peter 3:7-13', 'Hebrews 9:27'],
    relatedPassages: ['Genesis 3:22-24', 'Luke 16:19-31'],
    relatedSections: ['S05', 'S22', 'S21', 'S13'],
    topicIds: ['intermediate-state', 'final-judgment', 'immortality'],
    sourceIds: ['irenaeus-against-heresies', 'dear-bible-teaches-annihilationism'],
    establishes: [
      'Scripture describes the unrighteous as kept until the day of judgment.',
      'Survival in the intermediate state is attributed to God sustaining, not to inherent immortality.',
    ],
    doesNotEstablish: [
      'The nature of conscious experience in the intermediate state.',
      'That the intermediate state is uniform for all the unrighteous.',
    ],
    caveats: [
      'Irenaeus makes a closely related point in the same chapter of Against Heresies where he discusses continuance being granted rather than possessed.',
    ],
    aliases: ['s09', 'delayed judgment', 'kept until judgment', 'sustained'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S10',
    canonicalOrder: 13,
    group: 'biblical-language',
    slug: 'body-and-soul',
    route: '/case/biblical-language/body-and-soul/',
    title: 'Can God Destroy Both Body and Soul?',
    question: 'What does Jesus say happens to the soul in Gehenna?',
    thesis:
      'In Matthew 10:28 Jesus ties the fate of the soul to the fate of the body and says God can destroy both. The comparison he draws is with killing, and the word he chooses for what God does is stronger, not weaker.',
    shortSummary:
      'Matthew 10:28 in its own terms, the use of the verb elsewhere in the Synoptics, and a technical appendix on two-part and three-part anthropology.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'reviewed',
    originalPages: [32, 33, 34, 35],
    sourceParagraphIds: ['p610', 'p611', 'p612', 'p613', 'p617', 'p618', 'p623', 'p642'],
    primaryPassages: ['Matthew 10:28', 'Luke 12:4-5'],
    relatedPassages: ['Revelation 20:14', 'Matthew 2:13', 'Mark 3:6', 'Luke 6:9', 'Isaiah 66:24'],
    relatedSections: ['S22', 'S08', 'S18', 'S07'],
    topicIds: ['body-soul-and-spirit', 'death', 'destruction', 'gehenna', 'second-death'],
    sourceIds: ['rethinking-hell', 'dear-bible-teaches-annihilationism'],
    ectPosition:
      'Defenders of eternal conscious torment read destroy here as ruin: God is able to consign the whole person, body and soul, to a condition of everlasting loss. The verse is taken to establish God’s authority over final destiny rather than the cessation of the person.',
    conditionalistResponse:
      'Jesus sets his statement alongside those who kill the body. When the same verb appears in the active voice in the Synoptics with one agent acting on another, it consistently refers to killing. Choosing that word here, in a comparison with killing, points in one direction.',
    establishes: [
      'Jesus ties the fate of body and soul together rather than separating them.',
      'The verb he uses is one that elsewhere describes putting a person to death.',
      'The comparison Jesus draws is with the ending of life, not with continued suffering.',
    ],
    doesNotEstablish: [
      'That the soul is not conscious in the intermediate state.',
      'Which anthropology, two-part or three-part, is correct.',
    ],
    caveats: [
      'The anthropological matrices from the source document are preserved in a technical subsection. Both two-part and three-part views are set out; neither is assumed.',
      'The word-usage argument is a pattern across nine instances, not a rule about what a word must mean.',
    ],
    aliases: [
      's10',
      'matthew 10:28',
      'body and soul',
      'destroy body and soul',
      'apollumi',
      'destroy soul and body',
    ],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S11',
    canonicalOrder: 14,
    group: 'biblical-language',
    slug: 'contrasts-with-eternal-life',
    route: '/case/biblical-language/contrasts-with-eternal-life/',
    title: 'What Scripture Contrasts with Eternal Life',
    question: 'When the New Testament names the alternative to eternal life, what does it say?',
    thesis:
      'The New Testament sets eternal life against perishing, death, passing away, not seeing life, wrath, condemnation, destruction and eternal punishment. Nine of these ten alternatives use the language of loss of life.',
    shortSummary:
      'The full list of contrasts, and why reading one of them as unending conscious life requires redefining the other nine.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'reviewed',
    originalPages: [35],
    sourceParagraphIds: ['p659', 'p660', 'p661', 'p670'],
    primaryPassages: ['John 3:16', 'John 3:36', 'Romans 6:23', 'Matthew 7:13-14'],
    relatedPassages: [
      'John 6:27',
      'John 10:28',
      '2 Peter 3:9',
      'John 5:24',
      '1 John 2:17',
      '1 John 5:12',
      'Romans 2:8',
      'John 5:29',
      'Matthew 7:23',
      'Galatians 6:8',
      'Matthew 25:46',
    ],
    relatedSections: ['S04', 'S08', 'S07', 'S22'],
    topicIds: ['eternal-life', 'perishing', 'death', 'destruction', 'punishment'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'The stated alternative to eternal life is overwhelmingly the language of losing life.',
      'Reading eternal punishment as unending conscious life makes it the odd one out.',
    ],
    doesNotEstablish: ['That any single one of these contrasts settles the question by itself.'],
    caveats: [
      'The count of ten contrasts is the author’s own tally from his reading, not a figure drawn from a published concordance study.',
    ],
    aliases: ['s11', 'contrasts with eternal life', 'perish', 'john 3:16', 'eternal life'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S12',
    canonicalOrder: 15,
    group: 'biblical-language',
    slug: 'no-explicit-ect-text',
    route: '/case/biblical-language/no-explicit-ect-text/',
    title: 'Where Is Endless Human Torment Stated Plainly?',
    question: 'Is there a text that plainly says wicked human beings suffer consciously for ever?',
    thesis:
      'No text states in so many words that wicked human beings will be tormented consciously without end. Given how much Scripture says about judgment and wrath, that silence is worth noticing.',
    shortSummary:
      'An argument from absence, stated with the limits an argument from absence carries.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'reviewed',
    originalPages: [36],
    sourceParagraphIds: ['p672', 'p673'],
    primaryPassages: ['Revelation 20:10-15', 'Revelation 14:9-11', 'Matthew 25:31-46'],
    relatedPassages: ['Mark 9:42-48', 'Daniel 12:2'],
    relatedSections: ['S01', 'S02', 'S03', 'S04', 'S08'],
    topicIds: ['eternal-conscious-torment', 'punishment'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    ectPosition:
      'Defenders of eternal conscious torment reply that the doctrine is stated plainly enough in Revelation 20:10 and 14:11, and that a demand for one particular form of words is an unreasonable standard no doctrine would meet.',
    conditionalistResponse:
      'The reply is fair as far as it goes, and those texts are treated at length elsewhere on this site. The observation here is comparative: the destruction vocabulary appears in scores of places in unambiguous terms, while the clearest statements for the traditional view are few and are contested.',
    establishes: [
      'The clearest traditional proof texts are few, and each is disputed on textual grounds.',
      'The destruction vocabulary is far more widespread and less contested.',
    ],
    doesNotEstablish: [
      'That eternal conscious torment is false. An argument from silence cannot carry that weight.',
    ],
    caveats: [
      'This is an argument from absence and is labelled a supporting argument for that reason. It has force only alongside the positive case.',
    ],
    aliases: ['s12', 'no explicit text', 'argument from silence', 'plainly stated'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S13',
    canonicalOrder: 16,
    group: 'biblical-pattern',
    slug: 'fire-consumes',
    route: '/case/biblical-patterns/fire-consumes/',
    title: 'What Fire Does in Scripture',
    question: 'When Scripture sets something on fire, what happens to it?',
    thesis:
      'Fire in Scripture consumes. Where something in a fire is not consumed, the text marks that as remarkable and attributes it to God preserving the thing. Fire as a preservative that keeps its fuel intact indefinitely is not a biblical picture.',
    shortSummary:
      'The ordinary function of fire in the biblical texts, the marked exceptions, and what fire paired with sulphur signifies.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'reviewed',
    originalPages: [36, 37],
    sourceParagraphIds: ['p676', 'p677', 'p678', 'p684', 'p690', 'p691'],
    primaryPassages: ['Matthew 13:24-43', 'Hebrews 12:29', 'Malachi 4:1-3'],
    relatedPassages: [
      'Exodus 3:2',
      'Isaiah 43:2',
      'Daniel 3:19-27',
      '1 Corinthians 3:11-15',
      'Luke 16:24',
      'Genesis 19:24-27',
      'Deuteronomy 29:22-23',
      'Isaiah 34:9-10',
      'Ezekiel 38:22',
      'Revelation 9:17-18',
    ],
    relatedSections: ['S01', 'S14', 'S03', 'S06', 'S08'],
    topicIds: ['fire', 'destruction', 'lake-of-fire'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    ectPosition:
      'Defenders of eternal conscious torment observe that the fire of final judgment is unlike ordinary fire in any case, and that God is entirely able to sustain a person within it, as he sustained the bush and the three men in the furnace.',
    conditionalistResponse:
      'God certainly can preserve something in fire, and Scripture records that he has. The point is that Scripture always marks those cases as extraordinary. The unmarked, ordinary function of fire, including in Jesus’ own parables of harvest and weeds, is to consume.',
    establishes: [
      'Consuming is the ordinary function of fire throughout Scripture.',
      'Preservation in fire is always presented as an exception requiring divine action.',
      'Fire paired with sulphur consistently marks complete destruction.',
    ],
    doesNotEstablish: [
      'That God could not sustain a person in the lake of fire if he chose to.',
      'That the lake of fire is literal rather than symbolic.',
    ],
    caveats: [],
    aliases: ['s13', 'fire', 'fire burns up', 'consuming fire', 'burned up'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S14',
    canonicalOrder: 17,
    group: 'biblical-pattern',
    slug: 'sodom-and-gomorrah',
    route: '/case/biblical-patterns/sodom-and-gomorrah/',
    title: 'Sodom and Gomorrah as the Example',
    question: 'What did Peter highlight when he called Sodom an example for the ungodly?',
    thesis:
      'Peter names Sodom and Gomorrah as an example of what is coming for the ungodly, and the two features he selects are that the cities were turned to ashes and condemned to extinction. Neither feature belongs to a picture of unending conscious torment.',
    shortSummary:
      'What Peter chose to highlight, what he could have highlighted instead, and what the cities were actually like the following morning.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'reviewed',
    originalPages: [37, 38],
    sourceParagraphIds: ['p693', 'p694', 'p695', 'p699', 'p702', 'p706', 'p716', 'p718'],
    primaryPassages: ['2 Peter 2:6', 'Jude 7', 'Genesis 19:24-28'],
    relatedPassages: [
      'Ezekiel 16:49-50',
      'Deuteronomy 29:23',
      'Jeremiah 49:18',
      'Zephaniah 2:9',
      'Isaiah 13:19-22',
      'Lamentations 4:6',
      'Matthew 10:15',
      'Luke 17:26-30',
    ],
    relatedSections: ['S13', 'S03', 'S15', 'S08'],
    topicIds: ['sodom-and-gomorrah', 'fire', 'destruction', 'eternal-and-everlasting'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    ectPosition:
      'Some interpreters holding eternal conscious torment argue that the example Peter has in view is not the physical destruction of the cities but what their inhabitants went on to experience, and that Jude’s phrase about eternal fire points beyond the historical event.',
    conditionalistResponse:
      'That reading sets aside the very features Peter names. He specifies ashes and extinction, both of which are observable historical facts about the cities. Jude’s eternal fire describes a fire whose effect is permanent: the cities were never rebuilt.',
    establishes: [
      'Peter selects being turned to ashes and being condemned to extinction as the example.',
      'Neither torment nor ongoing burning is mentioned in any passage about Sodom.',
      'Eternal fire in Jude describes permanence of effect, not duration of burning.',
    ],
    doesNotEstablish: [
      'That the inhabitants of Sodom experienced no suffering during the judgment.',
      'What the inhabitants of Sodom are experiencing now, before the final judgment.',
    ],
    caveats: [
      'Jesus says it will be more bearable for Sodom on the day of judgment than for some other towns, which shows the final judgment is still ahead for them.',
    ],
    aliases: ['s14', 'sodom', 'sodom and gomorrah', '2 peter 2:6', 'eternal fire'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S15',
    canonicalOrder: 18,
    group: 'biblical-pattern',
    slug: 'old-testament-judgment',
    route: '/case/biblical-patterns/old-testament-judgment/',
    title: 'Patterns of Judgment in the Old Testament',
    question: 'When God judges in the Old Testament, what form does the judgment take?',
    thesis:
      'The Old Testament pattern of divine judgment is comprehensive removal: the flood, Sodom, Korah, the devoted nations, the death penalty for the gravest offences. Prolonged torture never appears as a form of judgment God commands or performs.',
    shortSummary:
      'The recurring shape of divine judgment in the Old Testament, and what the Valley of Hinnom contributes to the word Gehenna.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'source-checked',
    originalPages: [38, 39],
    sourceParagraphIds: ['p719', 'p720', 'p721', 'p726', 'p732', 'p733', 'p735'],
    primaryPassages: ['Genesis 6:5-8', 'Deuteronomy 7:1-2', 'Jeremiah 7:32-33'],
    relatedPassages: [
      'Genesis 19:24-28',
      'Exodus 12:29-30',
      'Numbers 16:35',
      'Numbers 21:2-3',
      '2 Kings 1:10',
      'Deuteronomy 20:16-17',
      'Ezekiel 12:20',
      'Joshua 6:17-24',
      'Joshua 8:22',
    ],
    relatedSections: ['S14', 'S16', 'S13', 'S08'],
    topicIds: ['gehenna', 'final-judgment', 'destruction', 'sodom-and-gomorrah'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'Divine judgment in the Old Testament repeatedly takes the form of complete removal.',
      'The gravest offences under the law carried a death penalty rather than prolonged punishment.',
      'Gehenna transliterates the Valley of Hinnom, associated in Jeremiah with unburied corpses.',
    ],
    doesNotEstablish: [
      'That temporal judgments determine the form of final judgment. The link is a pattern, not a proof.',
    ],
    caveats: [
      'The claim that Gehenna was a burning rubbish dump in the first century is not supported by primary evidence and is not repeated here. The well-attested associations with the Valley of Hinnom, child sacrifice, slaughter and unburied bodies are.',
      'The source document’s suggestion that Satan therefore wants people to believe in torment is not part of the biblical case and is not reproduced. It is recorded in the migration ledger.',
    ],
    aliases: ['s15', 'old testament judgment', 'gehenna', 'valley of hinnom', 'flood'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S16',
    canonicalOrder: 19,
    group: 'biblical-pattern',
    slug: 'sacrificial-system',
    route: '/case/biblical-patterns/sacrificial-system/',
    title: 'What the Sacrificial System Says About Sin’s Penalty',
    question: 'What did the sacrifices do, and what did that say sin costs?',
    thesis:
      'Under the sacrificial system, atonement was made by the death of the animal. The life, carried in the blood, was what made atonement. The system says the cost of sin is a life, not a duration of suffering.',
    shortSummary:
      'What the sacrifices actually did, and what that establishes about the penalty they stood in for.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'reviewed',
    originalPages: [39],
    sourceParagraphIds: ['p737', 'p738', 'p739', 'p740'],
    primaryPassages: ['Leviticus 17:11', 'Hebrews 10:1-14'],
    relatedPassages: ['Hebrews 9:22', 'Genesis 22:1-14'],
    relatedSections: ['S17', 'S07', 'S26'],
    topicIds: ['death', 'punishment'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'Atonement under the law was made by the death of the sacrifice.',
      'The blood made atonement because the life of the creature is in it.',
      'Sacrificial animals were killed rather than subjected to prolonged suffering.',
    ],
    doesNotEstablish: [
      'That the sacrifices exhaustively picture every dimension of final judgment.',
    ],
    caveats: [],
    aliases: ['s16', 'sacrifice', 'sacrificial system', 'leviticus 17:11', 'atonement'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S17',
    canonicalOrder: 20,
    group: 'biblical-pattern',
    slug: 'jesus-death',
    route: '/case/biblical-patterns/jesus-death/',
    title: 'What Jesus’ Death Says About the Penalty for Sin',
    question: 'If Jesus died in our place, what was he standing in the place of?',
    thesis:
      'Jesus died for us. If his death was substitutionary, then what it substituted for was death. Had endless conscious suffering been the penalty, his death would be difficult to account for.',
    shortSummary:
      'The substitution argument, the foreshadowing in Genesis 22, and the way Jesus’ final day traces the shape of judgment.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'reviewed',
    originalPages: [39, 40],
    sourceParagraphIds: ['p741', 'p742', 'p743', 'p746', 'p749', 'p756', 'p764'],
    primaryPassages: ['Romans 5:8', 'Romans 3:25', '1 Corinthians 15:3'],
    relatedPassages: [
      'Genesis 22:1-14',
      'Matthew 27:46',
      'Matthew 26:39',
      'Hebrews 9:22',
      'Matthew 3:17',
    ],
    relatedSections: ['S16', 'S07', 'S18', 'S26', 'S02'],
    topicIds: ['death', 'punishment', 'second-death'],
    sourceIds: ['dear-bible-teaches-annihilationism', 'welch-source-document'],
    ectPosition:
      'Defenders of eternal conscious torment reply that Christ, being of infinite worth, could bear in a finite time what would otherwise take his people for ever, and that his suffering as well as his death is redemptive.',
    conditionalistResponse:
      'If the infinite worth of the sufferer compresses an infinite penalty into a finite time, it is not clear why the death was required at all. Scripture states repeatedly that he died for our sins, and that without the shedding of blood there is no forgiveness.',
    establishes: [
      'Scripture consistently identifies the death of Christ, not merely his suffering, as what saves.',
      'The binding of Isaac foreshadows a substitutionary death rather than a substitutionary torment.',
    ],
    doesNotEstablish: [
      'That the suffering of Christ was incidental to the atonement.',
      'That Christ was annihilated. He was not, and the page says so explicitly.',
    ],
    caveats: [
      'The reading of Jesus’ final day as a picture of the day of judgment is offered by the author as a side idea, and is labelled a theological inference rather than a direct argument.',
      'The source document’s table of contents numbers this section 18 while the body numbers it 17. The body headings are canonical here.',
    ],
    aliases: ['s17', 'jesus death', 'the cross', 'substitution', 'died for us'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S18',
    canonicalOrder: 21,
    group: 'biblical-pattern',
    slug: 'physical-and-final-death',
    route: '/case/biblical-patterns/physical-and-final-death/',
    title: 'Physical Death as a Picture of Final Death',
    question: 'If physical death pictures something, what does it picture?',
    thesis:
      'When a person dies physically they no longer consciously exist in the physical world. If the physical points to the spiritual, the second death is the corresponding loss in the spiritual realm. And if death means separation, separation from the sustainer of all things has the same result.',
    shortSummary:
      'The parallel between the first and second deaths, and why the separation definition leads to the same place.',
    evidenceRole: 'theological-inference',
    reviewStatus: 'reviewed',
    originalPages: [40],
    sourceParagraphIds: ['p766', 'p767', 'p768', 'p769'],
    primaryPassages: ['Revelation 20:14', 'James 2:26'],
    relatedPassages: ['Hebrews 1:3', 'Colossians 1:17', '1 Corinthians 8:6'],
    relatedSections: ['S07', 'S17', 'S10', 'S22'],
    topicIds: ['death', 'second-death', 'body-soul-and-spirit'],
    sourceIds: ['dear-bible-teaches-annihilationism', 'welch-source-document'],
    ectPosition:
      'Defenders of eternal conscious torment hold that death in Scripture means separation rather than cessation, and that the second death is therefore permanent separation from God, consciously experienced.',
    conditionalistResponse:
      'Take separation as the definition and the conclusion still follows. Christ is the one in whom all things hold together. A creature genuinely separated from the source and sustainer of life is not thereby sustained.',
    establishes: [
      'The separation definition of death does not by itself secure continued existence.',
      'Physical death is a natural picture of the loss the second death names.',
    ],
    doesNotEstablish: [
      'That the parallel between physical and final death is exact in every respect.',
    ],
    caveats: [
      'This is an inference from a pattern, not a statement Scripture makes in these terms, and it is labelled as such.',
      'The source document’s table of contents numbers this section 17 while the body numbers it 18. The body headings are canonical here.',
    ],
    aliases: ['s18', 'physical death', 'second death', 'separation'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S19',
    canonicalOrder: 22,
    group: 'final-destiny',
    slug: 'not-opposites',
    route: '/case/final-destiny/not-opposites/',
    title: 'Hell Is Not the Opposite of Heaven',
    question: 'Are the two destinies symmetrical?',
    thesis:
      'Paul insists the gift is not like the trespass. Scripture does not present the two destinies as mirror images of equal weight in opposite directions, and a symmetry the text denies should not be built into a doctrine of final punishment.',
    shortSummary:
      'Why Romans 5 refuses the symmetry, and what follows for how the two destinies are imagined.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'reviewed',
    originalPages: [41],
    sourceParagraphIds: ['p771', 'p772', 'p773', 'p774', 'p775'],
    primaryPassages: ['Romans 5:15-18'],
    relatedPassages: ['Matthew 7:13-14'],
    relatedSections: ['S20', 'APP2', 'APP1', 'P00'],
    topicIds: ['eternal-life', 'eternal-conscious-torment', 'punishment'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'Paul explicitly denies that the gift and the trespass are comparable in kind.',
      'Treating the two destinies as equal opposites is a theological assumption, not a biblical statement.',
    ],
    doesNotEstablish: ['That final punishment is light. Asymmetry does not mean triviality.'],
    caveats: [
      'The net-outcome argument that appears at this point in the source document is philosophical rather than biblical. It is preserved in Appendix 2 and labelled accordingly.',
    ],
    aliases: ['s19', 'hell is not the opposite of heaven', 'dualism', 'romans 5'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S20',
    canonicalOrder: 23,
    group: 'final-destiny',
    slug: 'no-place-prepared',
    route: '/case/final-destiny/no-place-prepared/',
    title: 'Why No Place Is Prepared for the Unrighteous',
    question: 'Who has a place prepared for them in Matthew 25?',
    thesis:
      'In Matthew 25 the righteous inherit a kingdom prepared for them, and the eternal fire was prepared for the devil and his angels. The unrighteous are the only group with no place prepared. If they were to exist for ever, that would be a striking omission.',
    shortSummary:
      'The three parties in Matthew 25, the parables where the righteous have a container and the wicked have none, and the limits of the argument.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'reviewed',
    originalPages: [41],
    sourceParagraphIds: ['p778', 'p779', 'p780', 'p784'],
    primaryPassages: ['Matthew 25:31-46'],
    relatedPassages: ['Matthew 13:24-43', 'Matthew 13:47-50', 'John 14:2-3'],
    relatedSections: ['S03', 'S19', 'S06', 'S21'],
    topicIds: ['lake-of-fire', 'final-judgment', 'eternal-life'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'Matthew 25 names a place prepared for the righteous and a place prepared for the devil.',
      'No place is described as prepared for wicked human beings.',
    ],
    doesNotEstablish: [
      'That the absence of a prepared place proves the unrighteous do not continue.',
    ],
    caveats: [
      'This is an argument from what a text does not say, and its weight depends on the wider case.',
    ],
    aliases: ['s20', 'no place prepared', 'matthew 25:34', 'prepared for the devil'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S21',
    canonicalOrder: 24,
    group: 'final-destiny',
    slug: 'tree-of-life',
    route: '/case/final-destiny/tree-of-life/',
    title: 'The Tree of Life and Conditional Life',
    question: 'Why were Adam and Eve barred from the tree?',
    thesis:
      'God barred the way to the tree of life and stated the reason: otherwise the man would eat and live for ever. The tree reappears in the New Jerusalem, inside the city, and those outside are explicitly excluded from it.',
    shortSummary:
      'What Genesis says the tree did, where it stands in Revelation, and which part of this argument is inference.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'reviewed',
    originalPages: [41, 42],
    sourceParagraphIds: ['p786', 'p787', 'p788', 'p789', 'p792', 'p794', 'p795'],
    primaryPassages: ['Genesis 3:22-24', 'Revelation 22:1-5', 'Revelation 22:14-15'],
    relatedPassages: ['Genesis 2:9', 'Revelation 2:7', 'Revelation 21:8'],
    relatedSections: ['RB2', 'S22', 'S28', 'S20'],
    topicIds: ['tree-of-life', 'immortality', 'eternal-life', 'conditional-immortality'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    ectPosition:
      'Defenders of eternal conscious torment generally hold that the tree of life concerns the quality and blessedness of life in God’s presence rather than bare continued existence, and that exclusion from it means exclusion from blessing rather than from being.',
    conditionalistResponse:
      'Genesis gives the reason for the exclusion in plain terms: lest he eat and live for ever. That connects the tree to continued life and not only to its quality. Revelation places the tree inside the city and names those who are outside it.',
    establishes: [
      'Genesis links access to the tree with living for ever, and gives that as the reason for exclusion.',
      'In Revelation the tree stands inside the city and the unrighteous are excluded from both.',
    ],
    doesNotEstablish: [
      'The mechanics of how resurrected bodies are sustained.',
      'That the tree is a literal tree rather than an image.',
    ],
    caveats: [
      'That resurrected bodies continue to receive life through the tree is a theological inference, not a statement Scripture makes. The exclusion argument does not depend on it.',
    ],
    aliases: ['s21', 'tree of life', 'genesis 3:22', 'revelation 22'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S22',
    canonicalOrder: 25,
    group: 'final-destiny',
    slug: 'conditional-immortality',
    route: '/case/final-destiny/conditional-immortality/',
    title: 'The Biblical Case for Conditional Immortality',
    question: 'Where does immortality come from, and who receives it?',
    thesis:
      'Scripture treats immortality as something God alone possesses and gives. Followers of Jesus exchange the perishable for the imperishable at the resurrection. Those who do not receive that gift are not thereby given a different kind of endless existence.',
    shortSummary:
      'The synthesis: 1 Corinthians 15 read through, and the short chain of reasoning from perishable bodies to the fate of the soul.',
    evidenceRole: 'core-biblical',
    reviewStatus: 'reviewed',
    originalPages: [42, 43],
    sourceParagraphIds: ['p796', 'p797', 'p800', 'p801', 'p802', 'p803', 'p808', 'p813'],
    primaryPassages: ['1 Corinthians 15', '1 Timothy 6:15-16', '2 Timothy 1:10'],
    relatedPassages: [
      '1 Peter 1:4',
      '1 Peter 1:23',
      'Romans 2:7',
      'Malachi 4:1-3',
      'Matthew 10:28',
    ],
    relatedSections: ['RB2', 'S21', 'S10', 'S09', 'S11'],
    topicIds: ['conditional-immortality', 'immortality', 'eternal-life', 'resurrection'],
    sourceIds: ['dear-bible-teaches-annihilationism', 'afterlife-god-alone-is-immortal'],
    establishes: [
      'Immortality is presented as God’s possession and God’s gift, not a human property.',
      'The imperishable body of 1 Corinthians 15 is described for those raised in Christ.',
      'The unrighteous are never said to be granted immortality.',
    ],
    doesNotEstablish: [
      'The precise nature of the resurrection body of the unrighteous.',
      'How long the unrighteous consciously exist after being raised.',
    ],
    caveats: [
      'The step from perishable bodies to the fate of the soul relies on Matthew 10:28 tying the two together, which is argued in S10 rather than assumed here.',
    ],
    aliases: ['s22', 'conditional immortality', '1 corinthians 15', 'immortality', 'imperishable'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S23',
    canonicalOrder: 26,
    group: 'further-reasoning',
    slug: 'day-of-judgment',
    route: '/case/further-reasoning/day-of-judgment/',
    title: 'The Day of Judgment',
    question: 'Is the day of judgment an event or the beginning of a condition?',
    thesis:
      'Scripture speaks of a day of judgment on which both the judging and the destruction of the ungodly occur. Jesus can say the day will be more bearable for one place than another, which treats what happens on that day as itself the punishment.',
    shortSummary: 'The language of a day, and what it means for when full justice is administered.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'reviewed',
    originalPages: [43, 44],
    sourceParagraphIds: ['p816', 'p817', 'p819', 'p822', 'p824', 'p839'],
    primaryPassages: ['2 Peter 3:7-13', 'Matthew 10:15', 'Romans 2:5'],
    relatedPassages: ['Zephaniah 1:15-18', '2 Peter 2:1', 'Hebrews 9:27'],
    relatedSections: ['RB3', 'S09', 'S24', 'S30'],
    topicIds: ['final-judgment', 'day-of-the-lord', 'punishment'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'Scripture locates judgment and the destruction of the ungodly on the same day.',
      'Jesus treats the day of judgment itself as the thing whose severity varies.',
    ],
    doesNotEstablish: [
      'The literal duration of the day of judgment.',
      'That the conscious punishment on that day is brief.',
    ],
    caveats: [
      'The comparison of how much glory accrues to God under each view is a theological reflection, not a biblical argument, and is presented as such.',
    ],
    aliases: ['s23', 'day of judgment', 'judgment day', 'day of the lord'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S24',
    canonicalOrder: 27,
    group: 'further-reasoning',
    slug: 'no-more-pain',
    route: '/case/further-reasoning/no-more-pain/',
    title: 'No More Death, Mourning, Crying, or Pain',
    question: 'Does the old order pass away, or is it relocated?',
    thesis:
      'Revelation 21:4 says the former things have passed away, using the same verb used a few lines earlier of the first heaven and the first earth. Those are not relocated. If death and pain pass away in the same sense, they do not continue elsewhere.',
    shortSummary:
      'The verb in Revelation 21, what it is applied to, and how far the argument reaches.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'reviewed',
    originalPages: [44],
    sourceParagraphIds: ['p840', 'p841', 'p842', 'p844', 'p845'],
    primaryPassages: ['Revelation 21:1-4'],
    relatedPassages: ['Ezekiel 33:11', '1 Corinthians 15:26'],
    relatedSections: ['S28', 'S25', 'S03'],
    topicIds: ['second-death', 'final-judgment', 'eternal-life'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'The same verb describes the passing of the first heaven and earth and of death and pain.',
      'Passing away in that sense is not relocation.',
    ],
    doesNotEstablish: [
      'That the promise in Revelation 21:4 is addressed to anyone other than the redeemed.',
    ],
    caveats: [
      'The question of whether the redeemed would grieve for the lost is a pastoral observation rather than an argument from the text.',
    ],
    aliases: ['s24', 'no more pain', 'revelation 21:4', 'former things passed away'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S25',
    canonicalOrder: 28,
    group: 'further-reasoning',
    slug: 'all-in-all',
    route: '/case/further-reasoning/all-in-all/',
    title: 'How “All in All” Fits After Final Judgment',
    question: 'What do the universal-sounding texts describe?',
    thesis:
      'The texts about God being all in all and uniting all things under Christ are not universalist, and this site does not teach universal salvation. They do read more naturally in a final state where the unrighteous no longer exist than in one where they persist in rebellion.',
    shortSummary:
      'Why the all texts do not teach universalism, and why they sit more easily with conditionalism than with unending rebellion.',
    evidenceRole: 'theological-inference',
    reviewStatus: 'reviewed',
    originalPages: [45],
    sourceParagraphIds: ['p846', 'p847', 'p848', 'p850', 'p852', 'p856'],
    primaryPassages: ['1 Corinthians 15:20-28', 'Ephesians 1:10'],
    relatedPassages: ['Romans 5:18', 'Romans 11:32', 'Romans 14:10-11', 'Philippians 2:10-11'],
    relatedSections: ['S28', 'S24', 'S22'],
    topicIds: ['universal-reconciliation', 'eternal-life', 'final-judgment'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'The universal-sounding texts are bounded by their contexts and do not teach universal salvation.',
      'A final state without persisting rebellion reads more naturally with the language of unity.',
    ],
    doesNotEstablish: ['That these texts are evidence for conditional immortality on their own.'],
    caveats: [
      'This page reasons about which final state the language fits more comfortably. That is an inference, and it is labelled as one.',
    ],
    aliases: ['s25', 'all in all', '1 corinthians 15:28', 'universalism', 'unity of all things'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S26',
    canonicalOrder: 29,
    group: 'further-reasoning',
    slug: 'suffering-does-not-pay',
    route: '/case/further-reasoning/suffering-does-not-pay/',
    title: 'Why Suffering Does Not Pay for Sin',
    question: 'If suffering discharged the debt, what would follow?',
    thesis:
      'If suffering could discharge the debt of sin, then a long enough punishment would eventually settle it and release would follow. Scripture names death as the wage, and the parable of the unforgiving servant does not suggest the debt gets paid in prison.',
    shortSummary:
      'Why treating suffering as payment leads toward universalism, and what the debt language actually implies.',
    evidenceRole: 'theological-inference',
    reviewStatus: 'reviewed',
    originalPages: [45],
    sourceParagraphIds: ['p862', 'p863', 'p864'],
    primaryPassages: ['Matthew 18:23-35', 'Romans 6:23'],
    relatedPassages: ['Hebrews 9:22'],
    relatedSections: ['S07', 'S16', 'S17', 'S30', 'RB3'],
    topicIds: ['punishment', 'death', 'universal-reconciliation'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'Treating suffering as payment implies the debt could eventually be discharged.',
      'Scripture names death rather than duration of suffering as the wage of sin.',
    ],
    doesNotEstablish: [
      'That suffering has no place in final judgment. Conditionalism holds that it does.',
    ],
    caveats: [
      'This is reasoning about the internal consistency of a position rather than exegesis of a text.',
    ],
    aliases: ['s26', 'suffering does not pay', 'unforgiving servant', 'debt'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S27',
    canonicalOrder: 30,
    group: 'further-reasoning',
    slug: 'better-not-born',
    route: '/case/further-reasoning/better-not-born/',
    title: '“Better for Him If He Had Not Been Born”',
    question: 'Why is that said of one man in particular?',
    thesis:
      'Jesus says it of Judas specifically, which implies it is not equally true of everyone. On the traditional view it would be true of every person who is lost, which makes the singling out difficult to account for.',
    shortSummary: 'A short argument from a single saying, and what it does and does not carry.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'reviewed',
    originalPages: [45, 46],
    sourceParagraphIds: ['p866', 'p867', 'p868', 'p870'],
    primaryPassages: ['Matthew 26:24'],
    relatedPassages: ['Mark 14:21'],
    relatedSections: ['RB3', 'S30', 'S25'],
    topicIds: ['punishment', 'final-judgment', 'universal-reconciliation'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'The saying distinguishes Judas from others, which implies degrees in final outcome.',
      'Degrees of punishment are difficult to express if every lost person faces an identical unending fate.',
    ],
    doesNotEstablish: [
      'That the saying is a technical statement about relative outcomes rather than a solemn warning.',
    ],
    caveats: [
      'Some interpreters read the saying as a Semitic idiom of extreme woe rather than a comparative judgment. That reading is noted on the page.',
    ],
    aliases: ['s27', 'better not born', 'judas', 'matthew 26:24'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S28',
    canonicalOrder: 31,
    group: 'objection',
    slug: 'revelation-after-20-15',
    route: '/objections/revelation-after-20-15/',
    title: 'Are the Wicked Still Present After Revelation 20?',
    question: 'Who are the people outside the city in Revelation 22?',
    thesis:
      'Revelation 21:8 and 22:15 describe the people presently characterised by those sins and what their portion is. They read most naturally as a recapitulation rather than as a report of people living alongside the New Jerusalem.',
    shortSummary:
      'The recapitulation reading, the promise that righteousness dwells in the new creation, and the tree-of-life argument for anyone who reads it literally.',
    evidenceRole: 'supporting-biblical',
    reviewStatus: 'reviewed',
    originalPages: [46],
    sourceParagraphIds: ['p873', 'p874', 'p876', 'p878', 'p880'],
    primaryPassages: ['Revelation 21:8', 'Revelation 22:14-15', '2 Peter 3:13'],
    relatedPassages: [
      'Revelation 21:1-4',
      '1 Corinthians 6:9-10',
      'Galatians 5:19-21',
      'Ephesians 5:5',
    ],
    relatedSections: ['S21', 'S24', 'S03'],
    topicIds: ['second-death', 'tree-of-life', 'final-judgment'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    ectPosition:
      'Interpreters who hold eternal conscious torment note that Revelation 22:15 says plainly that certain people are outside, after the New Jerusalem has descended, and take this as evidence that the lost still exist in the new creation.',
    conditionalistResponse:
      'The immediately preceding line addresses those who wash their robes, which is something done now rather than after the judgment. The passage is describing present people and their portion. And even read as a literal moment, those outside have no access to the tree of life.',
    establishes: [
      'The surrounding verses address present readers and present conduct.',
      'The new creation is described as the place where righteousness dwells.',
    ],
    doesNotEstablish: [
      'That the recapitulation reading is the only possible reading of these verses.',
    ],
    caveats: [],
    aliases: ['s28', 'outside the city', 'revelation 22:15', 'after revelation 20'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S29',
    canonicalOrder: 32,
    group: 'objection',
    slug: 'evangelism',
    route: '/objections/evangelism/',
    title: 'Would Conditional Immortality Weaken Evangelism?',
    question: 'Does a shorter punishment lower the stakes?',
    thesis:
      'Whether a doctrine helps or hinders evangelism has no bearing on whether it is true. And on this view the stakes remain absolute: the loss is everything a person could have had, permanently.',
    shortSummary:
      'The truth question separated from the pastoral one, and what actually motivates the call to repentance in the New Testament.',
    evidenceRole: 'further-consideration',
    reviewStatus: 'reviewed',
    originalPages: [46, 47],
    sourceParagraphIds: ['p882', 'p883', 'p885', 'p887', 'p889'],
    primaryPassages: ['1 Timothy 2:4', '2 Peter 3:9', 'Matthew 23:37'],
    relatedPassages: ['Ezekiel 18:23', 'Matthew 4:17'],
    relatedSections: ['P00', 'S30', 'S23'],
    topicIds: ['eternal-life', 'eternal-conscious-torment'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'The consequences of holding a doctrine are not evidence for or against its truth.',
      'The New Testament grounds the call to repentance in the nearness of the kingdom.',
    ],
    doesNotEstablish: [
      'That conditionalism in fact produces more or less evangelism. No such study is cited.',
    ],
    caveats: [
      'This page is a pastoral reflection and is labelled a further consideration rather than an argument.',
    ],
    aliases: ['s29', 'evangelism', 'sharing the gospel', 'motivation'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S30',
    canonicalOrder: 33,
    group: 'objection',
    slug: 'is-annihilation-punishment',
    route: '/objections/is-annihilation-punishment/',
    title: 'Is Annihilation Really Punishment?',
    question: 'If the wicked cease to exist, in what sense have they been punished?',
    thesis:
      'The final judgment is consciously experienced, severe, and to be avoided at all costs. And even setting aside what is suffered, the permanent and irreversible removal of everything a person could have had is precisely what makes a death sentence the gravest penalty.',
    shortSummary:
      'Two answers: finite experiences genuinely matter, and exclusion from eternal life is itself the ultimate loss.',
    evidenceRole: 'further-consideration',
    reviewStatus: 'reviewed',
    originalPages: [47],
    sourceParagraphIds: ['p895', 'p896', 'p897', 'p898', 'p899', 'p902', 'p903', 'p904'],
    primaryPassages: ['Zephaniah 1:15-18', 'Matthew 25:46'],
    relatedPassages: ['Matthew 13:41-42', '2 Thessalonians 1:5-10'],
    relatedSections: ['S04', 'S06', 'S23', 'S26'],
    topicIds: ['punishment', 'final-judgment', 'second-death'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    ectPosition:
      'A common objection holds that ceasing to exist cannot be a punishment at all, since there is no one left to undergo it, and that conditionalism therefore empties the warnings of Scripture of their force.',
    conditionalistResponse:
      'Conditionalism does not teach that the wicked simply stop existing on the day of judgment. It teaches that they are raised, judged, and punished consciously, and that the punishment culminates in death. The objection describes a view this site does not hold.',
    establishes: [
      'Conditional immortality affirms conscious, severe and proportionate punishment.',
      'The gravity of a death sentence lies in irreversible loss, not only in pain inflicted.',
    ],
    doesNotEstablish: ['The duration or intensity of what any individual consciously experiences.'],
    caveats: [],
    aliases: ['s30', 'is annihilation punishment', 'painless', 'cease to exist', 'just disappear'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S31',
    canonicalOrder: 34,
    group: 'objection',
    slug: 'image-bearers',
    route: '/objections/image-bearers/',
    title: 'Would God Destroy His Image-Bearers?',
    question: 'Would God bring to nothing the crown of his own creation?',
    thesis:
      'The objection is right that human beings are the crown of creation and bear God’s image. What does not follow is that God must therefore sustain a broken image-bearer for ever in a state of ruin.',
    shortSummary:
      'The good instinct behind the objection, taken seriously, and why it does not lead where the objection supposes.',
    evidenceRole: 'theological-inference',
    reviewStatus: 'reviewed',
    originalPages: [47, 48],
    sourceParagraphIds: ['p907', 'p908', 'p909', 'p911', 'p913'],
    primaryPassages: ['1 Corinthians 11:7', 'Romans 3:23', '2 Corinthians 3:18'],
    relatedPassages: ['2 Corinthians 4:4', 'Colossians 1:15', 'Genesis 1:26-27'],
    relatedSections: ['RB2', 'S08', 'S22'],
    topicIds: ['image-of-god', 'destruction', 'immortality'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    ectPosition:
      'The objection, associated with Hank Hanegraaff among others, is that annihilating a bearer of the divine image would be a defeat for the Creator, and that God would not undo what he called very good.',
    conditionalistResponse:
      'It is not obvious why sustaining an image-bearer for ever in ruin honours the image more than removing what has been irreparably broken. Scripture repeatedly says God will destroy the wicked, and never says he is unwilling to.',
    establishes: [
      'The premise that human beings bear God’s image is affirmed rather than denied.',
      'Nothing in Scripture states that God will not destroy those who reject him.',
    ],
    doesNotEstablish: ['A complete theology of the image of God in the final state.'],
    caveats: [
      'This page reasons theologically about an objection rather than exegeting a passage, and is labelled an inference.',
    ],
    aliases: ['s31', 'image bearers', 'crowning jewel', 'hanegraaff'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S32',
    canonicalOrder: 35,
    group: 'objection',
    slug: 'satan-and-angels',
    route: '/objections/satan-and-angels/',
    title: 'Why Might Satan and His Angels Have a Different Fate?',
    question: 'Why would the same lake of fire do different things?',
    thesis:
      'The author holds that Satan and his angels differ from human beings in two ways relevant to judgment: they are not described as dependent creatures needing to be sustained, and they rebelled with unclouded knowledge. Other conditionalists disagree and hold that they too are destroyed.',
    shortSummary:
      'The author’s reasons, the alternative conditionalist position stated fairly, and why the human case does not depend on this.',
    evidenceRole: 'theological-inference',
    reviewStatus: 'alternative-conditionalist-reading',
    originalPages: [48],
    sourceParagraphIds: ['p914', 'p915', 'p916', 'p917', 'p918', 'p919'],
    primaryPassages: ['Revelation 20:10', 'Matthew 25:41', '1 Corinthians 13:12'],
    relatedPassages: ['1 Corinthians 15:24-26', '2 Peter 2:4', 'Jude 6'],
    relatedSections: ['S03', 'RB3', 'RB2'],
    topicIds: ['lake-of-fire', 'punishment', 'immortality'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    ectPosition:
      'Defenders of eternal conscious torment take Revelation 20:10 at face value for all who enter the lake of fire, and see no warrant for treating human beings differently from the devil.',
    conditionalistResponse:
      'Conditionalists divide here. The author holds that the devil and his angels differ in nature and in culpability. Joseph Dear, among others, holds that Revelation 20:10 belongs to a symbolic vision and that the devil is destroyed as well.',
    establishes: [
      'Conditionalists genuinely differ on the fate of Satan and the fallen angels.',
      'The case for human conditional immortality does not depend on resolving this.',
    ],
    doesNotEstablish: [
      'That angels are inherently immortal. Scripture does not say so directly.',
      'Which of the two conditionalist readings of Revelation 20:10 is correct.',
    ],
    caveats: [
      'The author states this is an area where he holds his view loosely and where he sees fewer practical implications.',
      'A speculative aside about angels and the experience of time is not treated as evidence and is recorded in the migration ledger.',
    ],
    aliases: ['s32', 'satan', 'devil', 'fallen angels', 'revelation 20:10'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S33',
    canonicalOrder: 36,
    group: 'objection',
    slug: 'near-death-experiences',
    route: '/objections/near-death-experiences/',
    title: 'What About Near-Death Experiences?',
    question: 'Should reported experiences of hell shape doctrine?',
    thesis:
      'Where a reported experience conflicts with Scripture, Scripture governs. That principle applies evenly: accounts of heaven that imply nearly everyone is saved are set aside on the same grounds as accounts of hell that reflect popular imagery.',
    shortSummary:
      'A methodological argument about how experience relates to Scripture, kept separate from empirical claims about what such accounts contain.',
    evidenceRole: 'further-consideration',
    reviewStatus: 'source-checked',
    originalPages: [48],
    sourceParagraphIds: ['p921', 'p922', 'p923', 'p926', 'p927'],
    primaryPassages: ['Luke 16:27-31', 'Matthew 7:13-14'],
    relatedPassages: ['Galatians 1:8', 'Isaiah 8:20'],
    relatedSections: ['S05', 'S30'],
    topicIds: ['intermediate-state', 'eternal-conscious-torment'],
    sourceIds: ['dear-bible-teaches-annihilationism'],
    establishes: [
      'A consistent method requires treating reported experiences of heaven and of hell alike.',
      'Scripture governs where a reported experience conflicts with it.',
    ],
    doesNotEstablish: [
      'Any empirical generalisation about what proportion of such accounts are positive.',
      'That such experiences do not occur, or that they have no other explanation.',
    ],
    caveats: [
      'The source document states that most such experiences are positive. This page does not repeat that as a quantitative claim, because no defined evidence base is cited for it.',
    ],
    aliases: ['s33', 'near death experiences', 'nde', 'visions of hell'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'S34',
    canonicalOrder: 37,
    group: 'objection',
    slug: 'jesus-heaven-versus-hell',
    route: '/objections/jesus-heaven-versus-hell/',
    title: 'Did Jesus Speak More About Hell Than Heaven?',
    question: 'Is the familiar claim about Jesus and hell accurate?',
    thesis:
      'The claim is repeated widely and is unlikely to be right, since Jesus speaks often of the kingdom and of eternal life. The specific ratio commonly quoted rests on one popular article whose method is not published, and this site does not assert it.',
    shortSummary:
      'Why the claim is doubtful, why the usual counter-figure is unverified, and what would be needed to settle it.',
    evidenceRole: 'further-consideration',
    reviewStatus: 'revision-needed',
    originalPages: [48, 49],
    sourceParagraphIds: ['p928', 'p929', 'p931', 'p933', 'p934'],
    primaryPassages: [],
    relatedPassages: ['Matthew 4:17', 'Matthew 13:44-46', 'John 3:16'],
    relatedSections: ['P00', 'S29'],
    topicIds: ['eternal-life', 'eternal-conscious-torment'],
    sourceIds: ['elliott-hell-vs-heaven'],
    establishes: [
      'The familiar claim that Jesus spoke more of hell than heaven is not well supported.',
    ],
    doesNotEstablish: [
      'The commonly quoted ratio of three to one. That figure is unverified here.',
    ],
    caveats: [
      'The source document relies on a single article for the count, and the author records in his own comments that he did not reproduce it. Until a count with published definitions and a dataset exists, this page states the modest claim only.',
      'Any such count depends on contested definitions: what counts as a reference to hell, whether kingdom language counts as heaven, and how Gospel parallels and repeated sayings are handled.',
    ],
    aliases: ['s34', 'jesus spoke more about hell', 'heaven versus hell', 'three times'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'APP1',
    canonicalOrder: 38,
    group: 'appendix',
    slug: 'afterlife-odds',
    route: '/appendix/afterlife-odds/',
    title: 'How Our View of the Outcomes Shapes Our Assumptions',
    question: 'Does the size of the stakes change what odds we assume?',
    thesis:
      'When people are shown a game with two outcomes and no stated probabilities, they infer the odds from the size of the outcomes. The illustration suggests that an extreme picture of final punishment can make people quietly assume they are unlikely to face it.',
    shortSummary:
      'A psychological illustration, with its assumptions stated, rebuilt as accessible tables and charts.',
    evidenceRole: 'further-consideration',
    reviewStatus: 'reviewed',
    originalPages: [50, 51],
    sourceParagraphIds: ['p953', 'p954', 'p955', 'p962', 'p968', 'p970', 'p973'],
    primaryPassages: ['Matthew 7:13-14'],
    relatedPassages: [],
    relatedSections: ['P00', 'S19', 'APP2'],
    topicIds: ['eternal-conscious-torment', 'eternal-life'],
    sourceIds: ['welch-source-document'],
    establishes: [
      'Outcome magnitude influences the probabilities people assume when none are given.',
    ],
    doesNotEstablish: [
      'Anything about what Scripture teaches. This is an analogy, not evidence.',
      'Any measured claim about what people actually believe about their own destiny.',
    ],
    caveats: [
      'This is a psychological and philosophical illustration. It is not empirical research and is not offered as support for the doctrine.',
      'The zero-sum assumption used to derive the presumed odds is stated explicitly on the page.',
    ],
    aliases: ['app1', 'appendix 1', 'afterlife odds', 'games', 'lottery'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
  {
    id: 'APP2',
    canonicalOrder: 39,
    group: 'appendix',
    slug: 'net-outcome-of-humanity',
    route: '/appendix/net-outcome-of-humanity/',
    title: 'The Net Outcome of Humanity Illustration',
    question: 'What happens if you try to sum the outcomes?',
    thesis:
      'The source document sets out an equation summing the experience of all people in both destinies. The author states plainly that the argument is philosophical and carries no weight against Scripture. It is preserved here on those terms.',
    shortSummary:
      'The equation, its assumptions, and the author’s own statement that it proves nothing.',
    evidenceRole: 'further-consideration',
    reviewStatus: 'reviewed',
    originalPages: [51, 52],
    sourceParagraphIds: ['p975', 'p977', 'p984', 'p988', 'p989', 'p995', 'p1000', 'p1003'],
    primaryPassages: ['Matthew 7:13-14', 'Romans 5:15-18'],
    relatedPassages: [],
    relatedSections: ['S19', 'APP1'],
    topicIds: ['eternal-conscious-torment', 'eternal-life'],
    sourceIds: ['welch-source-document'],
    establishes: [
      'Under a symmetrical view of the two destinies, the summed outcome is dominated by the larger group.',
    ],
    doesNotEstablish: [
      'Anything about what Scripture teaches. The author states this himself.',
      'That arithmetic on infinite quantities of this kind is well defined.',
    ],
    caveats: [
      'The source document labels this argument as purely philosophical and says it really holds no weight. That label is preserved prominently.',
      'The treatment of infinity here is informal. The page states the assumptions rather than presenting the result as a proof.',
    ],
    aliases: ['app2', 'appendix 2', 'net outcome', 'equation'],
    firstPublished: '2026-07-29',
    lastReviewed: '2026-07-29',
    lastSubstantiveRevision: '2026-07-29',
  },
]
