import type { SourceRecord } from '@ci/content-schema'

/**
 * The source library.
 *
 * Every hyperlink in the original document has a record here, including the
 * ones that were replaced by a more authoritative location. `sourceDocumentUrl`
 * preserves the original link so its disposition is traceable even when `url`
 * now points somewhere better.
 *
 * `rightsStatus` governs how much of a source may appear on the public site.
 * Anything not `public-domain` is paraphrased or quoted only briefly with
 * attribution; nothing under copyright is reproduced at length.
 */
export const SOURCE_RECORDS: readonly SourceRecord[] = [
  /* ---------------- The source document itself ---------------- */
  {
    id: 'welch-source-document',
    type: 'source-document',
    author: 'Phil Welch',
    title:
      'My case for Conditional Immortality/Annihilation (CI) instead of Eternal Conscious Torment (ECT)',
    date: '2023-03-01',
    edition: 'Working document, revised through 2026',
    perspective: 'CI',
    rightsStatus: 'cleared',
    linkStatus: 'not-checked',
    citedBy: ['P00', 'APP1', 'APP2'],
    note: 'The canonical source for this web edition. Held privately; the raw file is not published because it contains personal contact details and private editorial comments.',
  },
  {
    id: 'welch-video-overview',
    type: 'video',
    author: 'Phil Welch',
    title:
      "37 Reasons Hell Isn't/Is Forever - Conditional Immortality Is Biblical Not Eternal Conscious Torment",
    publication: 'YouTube',
    date: '2025-03-06',
    locator: '28 minutes 32 seconds',
    perspective: 'CI',
    url: 'https://youtu.be/9fevXbKUKmE',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'cleared',
    citedBy: [],
    note: 'The featured video overview. Its published English caption track is the basis for the transcript on the watch page.',
  },

  /* ---------------- Early church and historical primary sources ---------------- */
  {
    id: 'irenaeus-against-heresies',
    type: 'primary-historical',
    author: 'Irenaeus of Lyons',
    title: 'Against Heresies',
    date: 'c. AD 174-189',
    locator: 'Book II, chapter 34, section 3',
    perspective: 'historical',
    url: 'http://www.prudencetrue.com/images/Irenaeus_Against_Heresies_Book_II.pdf',
    sourceDocumentUrl: 'http://www.prudencetrue.com/images/Irenaeus_Against_Heresies_Book_II.pdf',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'public-domain',
    citedBy: ['RB1', 'S09'],
    note: 'Irenaeus argues that continued existence is granted by God rather than possessed by nature, and that the ungrateful creature forfeits it. The nineteenth-century Ante-Nicene Fathers translation is in the public domain.',
  },
  {
    id: 'ignatius-magnesians',
    type: 'primary-historical',
    author: 'Ignatius of Antioch',
    title: 'Epistle to the Magnesians',
    date: 'c. AD 107',
    locator: 'Chapter 10',
    perspective: 'historical',
    accessedAt: '2026-07-29',
    linkStatus: 'not-checked',
    rightsStatus: 'public-domain',
    citedBy: ['RB1'],
    note: 'Cited for the clause about ceasing to be if rewarded according to works. The longer and shorter recensions of the Ignatian corpus differ, which is noted on the page.',
  },
  {
    id: 'augustine-enchiridion',
    type: 'primary-historical',
    author: 'Augustine of Hippo',
    title: 'Enchiridion',
    publication: 'Nicene and Post-Nicene Fathers, First Series, Volume 3',
    publisher: 'Christian Literature Publishing Co.',
    date: '1887',
    edition: 'ed. Philip Schaff',
    locator: 'Chapter 112, page 273',
    perspective: 'historical',
    url: 'https://archive.org/details/aselectlibrary03unknuoft',
    sourceDocumentUrl: 'https://archive.org/details/aselectlibrary03unknuoft',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'public-domain',
    citedBy: ['RB1'],
    note: 'Augustine records that very many in his day rejected eternal torment. Reference supplied by Joseph Dear in the source document comments.',
  },
  {
    id: 'aquinas-summa-1a2ae-87',
    type: 'primary-historical',
    author: 'Thomas Aquinas',
    title: 'Summa Theologica',
    date: 'c. 1265-1274',
    locator: 'Ia-IIae, q. 87, a. 4, objection 2',
    perspective: 'ECT',
    url: 'https://www.newadvent.org/summa/2087.htm',
    sourceDocumentUrl: 'https://www.newadvent.org/summa/2087.htm',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'public-domain',
    citedBy: ['RB3'],
    note: 'Frequently quoted as Aquinas asserting that sin against an infinite God deserves infinite punishment. In context it is an objection Aquinas states and then answers. This correction was raised by Joseph Dear and accepted by the author.',
  },
  {
    id: 'edwards-justice-of-god',
    type: 'primary-historical',
    author: 'Jonathan Edwards',
    title: 'The Justice of God in the Damnation of Sinners',
    date: '1734',
    perspective: 'ECT',
    accessedAt: '2026-07-29',
    linkStatus: 'not-checked',
    rightsStatus: 'public-domain',
    citedBy: ['RB3'],
    note: 'Quoted briefly for the classic statement that obligation is proportioned to the dignity of the one obligating, and that sin against God is therefore infinitely heinous.',
  },
  {
    id: 'history-in-the-bible-fathers',
    type: 'website',
    title: 'Early Church Fathers and writings, chronological table',
    publication: 'History in the Bible',
    perspective: 'reference',
    url: 'https://www.historyinthebible.com/supplementary_pages/church_fathers.html',
    sourceDocumentUrl: 'https://www.historyinthebible.com/supplementary_pages/church_fathers.html',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['RB1'],
    note: 'Supplied the chronology and biographical notes for the early-church table in the source document. Used for dating only; the classifications on this site come from the primary texts.',
  },
  {
    id: 'truth-according-to-scripture-apostolic-fathers',
    type: 'website',
    title: 'Immortality and the Apostolic Fathers',
    publication: 'Truth According to Scripture',
    perspective: 'CI',
    url: 'https://www.truthaccordingtoscripture.com/documents/death/immortality-early-church/apostolic-fathers.php',
    sourceDocumentUrl:
      'https://www.truthaccordingtoscripture.com/documents/death/immortality-early-church/apostolic-fathers.php',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['RB1'],
    note: 'A conditionalist survey of the apostolic fathers. Treated as a conditionalist advocacy source, not as a neutral authority; the primary texts are cited directly alongside it.',
  },
  {
    id: 'church-fathers-conditionalists-video',
    type: 'video',
    title: 'Church Fathers who were Conditionalists',
    publication: 'YouTube',
    locator: 'approximately 13 minutes',
    perspective: 'CI',
    url: 'https://youtu.be/je3AW6QeXzk',
    sourceDocumentUrl: 'https://youtu.be/je3AW6QeXzk',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['RB1'],
    note: 'A short overview of early-church conditionalism, carried over from the source document as a further-reading link.',
  },

  /* ---------------- Conditionalist scholarship ---------------- */
  {
    id: 'dear-bible-teaches-annihilationism',
    type: 'book',
    author: 'Joseph Dear',
    title: 'The Bible Teaches Annihilationism',
    edition: '1st edition, PDF version',
    date: '2016',
    locator: 'approximately 590 pages',
    perspective: 'CI',
    url: 'https://www.3ringbinder.org/uploads/1/9/1/0/1910989/the_bible_teaches_annihilationism__1st_edition_pdf_version__final.pdf',
    sourceDocumentUrl:
      'https://www.3ringbinder.org/uploads/1/9/1/0/1910989/the_bible_teaches_annihilationism__1st_edition_pdf_version__final.pdf',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'quoted-briefly',
    citedBy: [
      'RB1',
      'RB2',
      'RB3',
      'S01',
      'S02',
      'S03',
      'S04',
      'S05',
      'S06',
      'S07',
      'S08',
      'S09',
      'S10',
      'S11',
      'S12',
      'S13',
      'S14',
      'S15',
      'S16',
      'S17',
      'S18',
      'S19',
      'S20',
      'S21',
      'S22',
      'S23',
      'S24',
      'S25',
      'S26',
      'S27',
      'S28',
      'S29',
      'S30',
      'S31',
      'S32',
      'S33',
    ],
    note: 'The most heavily used secondary source in the original document. Distributed free by the author as a PDF. Quoted briefly with page locators and otherwise paraphrased.',
  },
  {
    id: 'rethinking-hell',
    type: 'website',
    title: 'Rethinking Hell',
    perspective: 'CI',
    url: 'https://rethinkinghell.com/',
    sourceDocumentUrl: 'http://rethinkinghell.com',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['S10'],
    note: 'The principal conditionalist publishing project. Cited as a conditionalist source rather than as a neutral reference.',
  },
  {
    id: 'rethinking-hell-worm-does-not-die',
    type: 'article',
    author: 'Chris Date',
    title: 'Their Worm Does Not Die: Annihilation and Mark 9:48',
    publication: 'Rethinking Hell',
    date: '2012-07-17',
    perspective: 'CI',
    url: 'https://rethinkinghell.com/2012/07/17/their-worm-does-not-die-annihilation-and-mark-948/',
    sourceDocumentUrl:
      'https://rethinkinghell.com/2012/07/17/their-worm-does-not-die-annihilation-and-mark-948/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['S01'],
    note: 'Detailed treatment of the undying worm in Isaiah 66 and Mark 9.',
  },
  {
    id: 'rethinking-hell-fire-not-quenched',
    type: 'article',
    author: 'Chris Date',
    title: 'The Fire Is Not Quenched: Annihilation and Mark 9:48, Part 2',
    publication: 'Rethinking Hell',
    date: '2012-11-20',
    perspective: 'CI',
    url: 'https://rethinkinghell.com/2012/11/20/the-fire-is-not-quenched-annihilation-and-mark-948-part-2/',
    sourceDocumentUrl:
      'https://rethinkinghell.com/2012/11/20/the-fire-is-not-quenched-annihilation-and-mark-948-part-2/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['S01'],
    note: 'Companion article on unquenchable fire in the Hebrew prophets.',
  },
  {
    id: 'rethinking-hell-finite-sins',
    type: 'article',
    title: 'What Are We to Make of Finite Sins Against an Infinite God?',
    publication: 'Rethinking Hell',
    date: '2016-05-28',
    perspective: 'CI',
    url: 'https://rethinkinghell.com/2016/05/28/what-are-we-to-make-of-finite-sins-against-an-infinite-god/',
    sourceDocumentUrl:
      'https://rethinkinghell.com/2016/05/28/what-are-we-to-make-of-finite-sins-against-an-infinite-god/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['RB3'],
    note: 'Includes the discussion of infinity that the source document draws on in Roadblock 3.',
  },
  {
    id: 'rethinking-hell-2-thess-1-9-part-1',
    type: 'article',
    title:
      'Annihilation in 2 Thessalonians 1:9, Part 1: Destroyed by the Glory of His Manifest Presence',
    publication: 'Rethinking Hell',
    date: '2016-11-14',
    perspective: 'CI',
    url: 'https://rethinkinghell.com/2016/11/14/annihilation-in-2-thessalonians-19-part-1-destroyed-by-the-glory-of-his-manifest-presence/',
    sourceDocumentUrl:
      'https://rethinkinghell.com/2016/11/14/annihilation-in-2-thessalonians-19-part-1-destroyed-by-the-glory-of-his-manifest-presence/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['S04'],
    note: 'Argues that the presence of the Lord is the source of the destruction rather than the place it occurs.',
  },
  {
    id: 'rethinking-hell-2-thess-1-9-part-2',
    type: 'article',
    title: 'Annihilation in 2 Thessalonians 1:9, Part 2: Separation or Obliteration?',
    publication: 'Rethinking Hell',
    date: '2016-12-05',
    perspective: 'CI',
    url: 'https://rethinkinghell.com/2016/12/05/annihilation-in-2-thess-1-9-part-2-separation-or-obliteration/',
    sourceDocumentUrl:
      'https://rethinkinghell.com/2016/12/05/annihilation-in-2-thess-1-9-part-2-separation-or-obliteration/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['S04'],
    note: 'The detailed Greek discussion of the preposition in 2 Thessalonians 1:9.',
  },
  {
    id: 'rethinking-hell-early-church',
    type: 'article',
    title:
      'Introduction to Evangelical Conditionalism: The Doctrine of Eternal Torment Was Not Universal in the Early Church',
    publication: 'Rethinking Hell',
    date: '2017-09-27',
    perspective: 'CI',
    url: 'https://rethinkinghell.com/2017/09/27/introduction-to-evangelical-conditionalism-the-doctrine-of-eternal-torment-was-not-universal-in-the-early-church/',
    sourceDocumentUrl:
      'https://rethinkinghell.com/2017/09/27/introduction-to-evangelical-conditionalism-the-doctrine-of-eternal-torment-was-not-universal-in-the-early-church/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['RB1'],
    note: 'Note the title claim is the narrow one: not universal. This site follows that narrower wording rather than a majority claim.',
  },
  {
    id: 'rethinking-hell-weeping-gnashing',
    type: 'article',
    title: 'Weeping and Gnashing of Teeth Do Not Indicate Eternal Torment',
    publication: 'Rethinking Hell',
    date: '2018-11-28',
    perspective: 'CI',
    url: 'https://rethinkinghell.com/2018/11/28/weeping-and-gnashing-of-teeth-do-not-indicate-eternal-torment/',
    sourceDocumentUrl:
      'https://rethinkinghell.com/2018/11/28/weeping-and-gnashing-of-teeth-do-not-indicate-eternal-torment/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['S06'],
    note: 'Extended treatment of the phrase across the Synoptic parables.',
  },
  {
    id: 'rethinking-hell-bible-fellowship-church',
    type: 'article',
    title:
      'Denominational Doctrine on Damnation: The Developing Story of the Bible Fellowship Church',
    publication: 'Rethinking Hell',
    date: '2024-04-21',
    perspective: 'CI',
    url: 'https://rethinkinghell.com/2024/04/21/denominational-doctrine-on-damnation-the-developing-story-of-the-bible-fellowship-church/',
    sourceDocumentUrl:
      'https://rethinkinghell.com/2024/04/21/denominational-doctrine-on-damnation-the-developing-story-of-the-bible-fellowship-church/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'quoted-briefly',
    citedBy: ['S02'],
    note: 'Source of the observation that the three symbols of Revelation 14:9-11 converge again in chapters 18 and 19 around the fall of Babylon.',
  },
  {
    id: 'wenham-case-for-conditional-immortality',
    type: 'academic',
    author: 'John Wenham',
    title: 'The Case for Conditional Immortality',
    date: '1996',
    locator: 'approximately 18 pages',
    perspective: 'CI',
    url: 'https://www.truthaccordingtoscripture.com/documents/death/conditional-immortality-wenham.php',
    sourceDocumentUrl:
      'https://www.truthaccordingtoscripture.com/documents/death/conditional-immortality-wenham.php',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: [],
    note: 'A widely cited evangelical statement of the position, originally presented at the 1991 Fourth Edinburgh Conference in Christian Dogmatics.',
  },
  {
    id: 'fudge-fire-that-consumes',
    type: 'book',
    author: 'Edward Fudge',
    title:
      'The Fire That Consumes: A Biblical and Historical Study of the Doctrine of Final Punishment',
    edition: '3rd edition',
    date: '2011',
    publisher: 'Cascade Books',
    locator: 'over 400 pages',
    perspective: 'CI',
    url: 'https://www.youtube.com/watch?v=AAm5ji95bBM',
    sourceDocumentUrl: 'https://www.youtube.com/watch?v=AAm5ji95bBM',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: [],
    note: 'The standard book-length conditionalist treatment. The linked video is a 69-minute presentation by the author; the book itself is in copyright and is referenced rather than quoted.',
  },
  {
    id: 'afterlife-god-alone-is-immortal',
    type: 'article',
    title: 'God Alone Is Immortal',
    publication: 'Afterlife (afterlife.co.nz)',
    perspective: 'CI',
    url: 'https://www.afterlife.co.nz/articles/god-alone-is-immortal/',
    sourceDocumentUrl: 'https://www.afterlife.co.nz/articles/god-alone-is-immortal/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['RB2', 'S22'],
    note: 'A longer treatment of 1 Timothy 6:16, carried over from the source document as further reading.',
  },
  {
    id: 'anthem-eastside-three-views',
    type: 'video',
    title: 'Three views of hell: a detailed study',
    publication: 'YouTube, Anthem Eastside',
    perspective: 'mixed',
    url: 'https://youtu.be/HPNY1uxXhvA',
    sourceDocumentUrl: 'https://www.youtube.com/@anthemeastside/videos',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: [],
    note: 'First video in a series comparing the three main positions. Listed in the original document under Other Resources.',
  },
  {
    id: 'sprinkle-introduction',
    type: 'video',
    author: 'Preston Sprinkle',
    title: 'Introduction to the annihilation view of hell',
    publication: 'YouTube',
    perspective: 'mixed',
    url: 'https://youtu.be/nemKBJoCoKI',
    sourceDocumentUrl: 'https://youtu.be/nemKBJoCoKI',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['P00'],
    note: 'The video through which the author first encountered the position in November 2022. Sprinkle is co-author of Erasing Hell with Francis Chan.',
  },

  /* ---------------- Eternal conscious torment and multi-view sources ---------------- */
  {
    id: 'macarthur-truth-about-hell',
    type: 'sermon',
    author: 'John MacArthur',
    title: 'The Truth About Hell',
    publication: 'Grace to You, sermon 80-376',
    date: '2011',
    perspective: 'ECT',
    url: 'https://www.gty.org/library/sermons-library/80-376/the-truth-about-hell',
    sourceDocumentUrl: 'https://www.gty.org/library/sermons-library/80-376/the-truth-about-hell',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'quoted-briefly',
    citedBy: ['RB3'],
    note: 'Used to state the traditional position in its own words, including the argument that the lost continue sinning and so the punishment never catches up with the sin.',
  },
  {
    id: 'themelios-destroyed-for-ever',
    type: 'academic',
    title:
      'Destroyed For Ever: An Examination of the Debates Concerning Annihilation and Conditional Immortality',
    publication: 'Themelios, The Gospel Coalition',
    perspective: 'mixed',
    url: 'https://www.thegospelcoalition.org/themelios/article/destroyed-for-ever-an-examination-of-the-debates-concerning-annihilation-and-conditional-immortality/',
    sourceDocumentUrl:
      'https://www.thegospelcoalition.org/themelios/article/destroyed-for-ever-an-examination-of-the-debates-concerning-annihilation-and-conditional-immortality/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: [],
    note: 'A scholarly survey of the debate from a journal that does not advocate conditionalism. Useful for readers who want the traditional side of the argument at length.',
  },

  /* ---------------- Language and reference tools ---------------- */
  {
    id: 'biblehub-apo-575',
    type: 'lexicon',
    title: 'Strong’s Greek 575: apo',
    publication: 'Bible Hub',
    perspective: 'lexical',
    url: 'https://biblehub.com/greek/apo_575.htm',
    sourceDocumentUrl: 'https://biblehub.com/greek/apo_575.htm',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['S04'],
    note: 'Consulted for the range of the preposition in 2 Thessalonians 1:9. A concordance entry is a starting point, not a substitute for a standard lexicon or grammar, and the page says so.',
  },
  {
    id: 'strongs-h2781',
    type: 'lexicon',
    title: 'Strong’s Hebrew 2781: cherpah',
    publication: 'Bible Hub',
    perspective: 'lexical',
    url: 'https://biblehub.com/hebrew/strongs_2781.htm',
    sourceDocumentUrl: 'https://biblehub.com/hebrew/strongs_2781.htm',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['S01'],
    note: 'Consulted for the word rendered shame or reproach in Daniel 12:2.',
  },
  {
    id: 'bible-gateway',
    type: 'website',
    title: 'Bible Gateway',
    perspective: 'reference',
    url: 'https://www.biblegateway.com/',
    sourceDocumentUrl: 'https://www.biblegateway.com/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'link-only',
    citedBy: ['S08'],
    note: 'Linked so readers can look up passages in licensed modern translations that this site cannot reproduce in full.',
  },
  {
    id: 'web-bible',
    type: 'biblical-text',
    title: 'World English Bible',
    publisher: 'Rainbow Missions, Inc.',
    edition: 'Public domain modern English revision of the American Standard Version',
    perspective: 'reference',
    url: 'https://worldenglish.bible/',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'public-domain',
    citedBy: [],
    note: 'The base text for full Scripture quotations on this site. Chosen because it is public domain, which allows a reference work of this size to quote at length without a licence.',
  },

  /* ---------------- Popular sources treated with caution ---------------- */
  {
    id: 'elliott-hell-vs-heaven',
    type: 'article',
    author: 'Ed Elliott',
    title: 'Did Jesus Talk More About Hell Than He Did Heaven?',
    publication: 'Medium',
    perspective: 'mixed',
    url: 'https://medium.com/@edelliott/did-jesus-talk-more-about-hell-than-he-did-heaven-7e6100b4df82',
    sourceDocumentUrl:
      'https://medium.com/@edelliott/did-jesus-talk-more-about-hell-than-he-did-heaven-7e6100b4df82',
    accessedAt: '2026-07-29',
    linkStatus: 'live',
    rightsStatus: 'quoted-briefly',
    citedBy: ['S34'],
    note: 'The origin of the three-to-one figure in the source document. The article does not publish its verse list, definitions or categorisation, so this site reports the claim as unverified rather than asserting the ratio.',
  },
  {
    id: 'tinyurl-share-link',
    type: 'website',
    title: 'Short link and QR code for the original document',
    perspective: 'reference',
    /*
     * The short link itself is deliberately not recorded here.
     *
     * It was, and `/sources/` rendered it as a link, the downloadable
     * bibliography printed it, and the search index carried it. It resolved in
     * one hop to the shared working document — the same file
     * `docs/rights-audit.md` withholds because it opens with a personal email
     * address and phone number and carries thirty editorial comments by named
     * third parties who did not consent to publication. Publishing the
     * shortener published the document.
     *
     * The record stays, because the migration ledger references the link and
     * the fact that it was retired is worth stating. Its destination is not
     * something a reader needs, and is not this site's to give.
     */
    accessedAt: '2026-07-29',
    linkStatus: 'not-checked',
    rightsStatus: 'link-only',
    citedBy: [],
    note: 'Retired, and deliberately not reproduced here: it pointed at the shared working document rather than at this site. The printable handout carries a newly generated QR code for the canonical site URL instead.',
  },
]
